// src/liturgyData.js

import { title } from "framer-motion/client";
// NEU: Übersetzungen für die Benutzeroberfläche (UI)
export const uiTranslations = {
    titles: {
        homeSubtitle: {
            de: "Koptisch-Orthodoxes Patriarchat Unna-Massen",
            ar: "بطريركية الأقباط الأرثوذكس أونا-ماسن"
        },
        chooseLiturgy: {
            de: "Wähle die Liturgie",
            ar: "اختر القداس"
        },
        settings: {
            de: "Einstellungen",
            ar: "الإعدادات"
        },
        appLanguage: {
            de: "App Sprache / لغة التطبيق",
            ar: "لغة التطبيق / App Sprache"
        },
        prayerLanguages: {
            de: "Gebetssprachen (Max 3)",
            ar: "لغات الصلاة (بحد أقصى 3)"
        },
        loading: {
            de: "Wird geladen...",
            ar: "جار التحميل..."
        },
        done: {
            de: "Fertig",
            ar: "تم"
        }
    },
    buttons: {
        agpeya: { de: "Agpeya", ar: "الأجبية" },
        liturgy: { de: "Liturgie", ar: "القداسات" },
        bible: { de: "Bibel", ar: "الكتاب المقدس" },
        basily: { de: "Basilius (Basily)", ar: "القداس الباسيلي" },
        kerollosy: { de: "Cyrillus (Kerollosy)", ar: "القداس الكيرلسي" },
        gregorios: { de: "Gregorios (8ere8orios)", ar: "القداس الغريغوري" },
        habashy: { de: "Äthiopisch (Habashy)", ar: "القداس الحبشي" }
    }
};
export const languages = {
    de: { label: "🇩🇪 Deutsch", default: true },
    ar: { label: "🇪🇬 Arabisch", default: true },
    cop_ar: { label: "Koptisch (Arabische Buchstaben)", default: true },
    cop_cop: { label: "Koptisch (Original)", default: false },
    ar_de: { label: "Arabisch (Deutsche Buchstaben)", default: false },
    cop_de: { label: "Koptisch (Deutsche Buchstaben)", default: false },
};

export const liturgies = {
    // --- BASILIUS LITURGIE ---
    basily: {
        title: {
            de: "Die Göttliche Liturgie des Hl. Basilius",
            ar: "القداس الإلهي للقديس باسيليوس"
        },
        content: [
            {
                id: 1,
                speaker: "Volk",
                cop_ar: "Eporo...",
                de: "Wir glauben an den einen Gott: Gott den Vater , den Allmächtigen, Schöpfer des Himmels und der Erde, alles Sichtbaren und Unsichtbaren.Wir glauben an den einen Herrn Jesus Christus , Gottes einzigen Sohn, geboren aus dem Vater vor aller Zeit Licht vom Lichte , wahrer Gott vom wahren Gott, gezeugt, nicht geschaffen, eines Wesens mit dem Vater; durch ihn ist alles geworden. , nicht geschaffen, eines Wesens mit dem Vater; durch ihn ist alles geworden.  Für uns Menschen und um unseres Heils willen ist er vom Himmel herabgestiegen. Er hat Fleisch angenommen durch den Heiligen Geist, von der Jungfrau Maria und ist Mensch geworden. Er wurde gekreuzigt unter Pontius Pilatus an unserer Statt,hat gelitten und ist begraben worden.Am dritten Tag auferstanden von den Toten gemäß der Schrift,aufgefahren in den Himmel, sitzt er zur Rechten seines Vaters Und so wird er wiederkommen in seiner Herrlichkeit, zu richten die Lebenden und die Toten, und seiner Herrschaft wird kein Ende sein.Ja, wir glauben an den Heiligen Geist, der Herr ist und lebendig macht, der aus dem Vater hervorgeht , der mit dem Vater und dem Sohn angebetet und verherrlicht wird. Er hat gesprochen durch die Propheten Wir glauben an die eine heilige, universale und apostolische Kirche. Wir bekennen die eine Taufe zur Vergebung der Sünden. Wir erwarten die Auferstehung der Toten und das Leben der kommenden Welt. Amen.",
                ar: "بالحقيقة نؤمن بإله واحد الله الآب ضابط الكل خالق السماء والأرض ما يُرى وما لا يُرى نؤمن برب واحد يسوع المسيح ابن الله الوحيد المولود من الآب قبل كل الدهور نور من نور إله حق من إله حق مولود غير مخلوق ، مساوٍ للآب فى الجوهـر الذى به كان كل شيء هذا الذى من أجلنا نحن البشر ومن أجل خلاصنا نزل من السماء وتجسد من الروح القدس ومن مريم العذراء وتأنس وصلب عنا على عهد بيلاطس البنطي تألم وقبر وقام من بين الاموات فى اليوم الثالث كما فى الكتب وصعد الى السموات وجلس عن يمين أبيه وأيضاً يأتى فى مجده ليدين الاحياء والاموات الذى ليس لملكه انقضاء نعم نؤمن بالروح القدس الرب المحيي المنبثق من الآب. نسجد له ونمجده مع الآب والابن الناطق فى الأنبياء وبكنيسة واحدة مقدسة جامعة رسولية ونعترف بمعمودية واحدة لمغفرة الخطايا وننتظر قيامة الأموات وحياة الدهر الآتى .آمين",
                cop_cop: "Ⲡϭⲟⲓⲥ...",
                ar_de: "Bel 7aqiqa no2men be elah wa7ed, Allah el Ab dabet el kol, 5aleq el sama wal ard, ma yora wa ma la yora. No2men be rab wa7ed Yassou3 el Massi7, Ebn Allah el wa7id, el mawloud men el Ab qabl kol el dohour. Nour men Nour, Elah 7aq men Elah 7aq, mawloud gheir ma5louq, mosawen lel Ab fel gawhar, allazy bihi kan kol shay2. Haza allazy men aglina na7n el bashar, wa men agl 5alasna, nazal men el sama, wa tagassad men el Ro7 el Qodos wa men Mariam el 3azra2 wa ta2anas. Wa soleb 3anna 3ala 3ahd Bilatos el Bonti, ta2alam wa qober wa qam men bein el amwat fel yom el thaleth kama fel kotob. Wa sa3ad ela el samawat, wa galas 3an yamin abih. Wa aydan ya2ti fi magdehi le yadin el a7ya2 wal amwat, allazy laysa le molkehi enqida2. Na3am no2men bel Ro7 el Qodos, el Rab el mo7yi, el monbathiq men el Ab. Nasgod lahu wa nomagedohu ma3 el Ab wal Ebn, el nateq fel anbya2. Wa be kanisa wa7da moqadasa game3a rasoulya. Wa na3taref be ma3moudia wa7da le maghferet el 5ataya. Wa nantazer qiyamat el amwat, wa 7ayat el dahr el aaty. Amin.",
                cop_de: "Ep-chois...",
            },
            {
                id: 2,
                speaker: "Volk",
                cop_ar: "Ke to pnevmati so...",
                de: "Und mit deinem Geiste.",
                ar: "ولروحك أيضاً",
                cop_cop: "Ⲕⲉ ⲧⲱ ⲡⲛⲉⲩⲙⲁⲧⲓ ⲥⲟⲩ",
                ar_de: "Wa li-ruhika aydan",
                cop_de: "Ke to pnewmati su...",
            },
        ],
    },

    // --- GREGORIOS LITURGIE (8ere8orios) ---
    gregorios: {
        title: {
            de: "Die Liturgie des Hl. Gregorios",
            ar: "القداس الغريغوري",
        },
        content: [
            {
                id: 1,
                speaker: "Priester",
                cop_de: "",
                de: "Betet",
                ar: "صلوا",
                cop_cop: "; Sl/l",
                ar_de: "",
                cop_ar: "إشلـــــــيل",
            },
            {
                id: 2,
                speaker: "Diakon",
                cop_de: "",
                de: "Erhebt euch zum Gebet",
                ar: "للصلاة قفوا",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إيه بى إبروس إفشى إسطاثى تيه",
            },
            {
                id: 3,
                sectionTitle: {
                    de: "Das Versöhnungsgebet",
                    ar: "صلاة الصلح"
                },
                speaker: "Priester",
                cop_de: "",
                de: "Der Friede seit mit allen",
                ar: "السلام لجميعكم",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إيرينى باسى",
            },
            {
                id: 4,
                speaker: "Volk",
                cop_de: "",
                de: "Und mit deinem Geiste",
                ar: "ولروحك أيضا",
                cop_cop: "",
                ar_de: "",
                cop_ar: "كيه طو إبنفماتى سو",
            },
            {
                id: 5,
                speaker: "priester",
                cop_de: "",
                de: "Der Du bist,der Du warst und der Du sein Wirst bis in Ewigkeit ,der Wesensgleiche,Mitthorneden und Gefährte des Schöpfers und Vaters Der Du aus alleiniger Güte den Menschen aus dem Nichts geschaffen hast und ihn ins Paradies der Freude gesetzt hast. Als er aber durch die Täuschung des Feindes und den Ungehorsam gegen Dein heiliges Gebot fiel  und Du ihn in die frühere Würde bringen wolltest hast Du weder einem Engel ,noch einem Erzengel,noch einem propheten unsere Erlösung  anvertraut. Sondern du hast selber ohne Veränderung Fleisch angenommen und bist Mensch geworden, und bist uns in allem gleich geworden außer allein in der Sünde Du wurdest uns ein Mittler bei dem Vater, du hast die trennende Wand niedergerissen und die alte Feindschaft aufgehoben.Du hast  die Irdischen mit den Himmlischen versöhnt und die zwei eins gemacht, nachdem du die Heilsordnung im Fleisch vollendet hast. Als du empor Himmel leiblich aufgefahren bist ,hast du alles mit deiner Gottheit erfüllt. Du hast zu deinen heiligen Jüngern und Aposteln gesagt Meinen Frieden gebe ich euch ,meinen Frieden hinterlasse ich euch. Gewähre ihn uns , unser Herr. Reinige uns von aller Befleckung, allem Betrug, aller Heuchelei, jeder listigen Tat und vom Denken an das Böse, das den Tod nach sich zieht.",
                ar: "أيها الكائن الذى كان الدائم إلي الأبد، الذاتي والمساوي والجليس والخالق الشريك مع الآأيها الكائن الذى كان الدائم إلي الأبد، الذاتي والمساوي والجليس والخالق الشريك مع الآب، الذى من أجل الصلاح وحده مما لم يكن كونت الانسان وجعلته في فردوس النعيم وعندما سقط بغواية العدو ومخالفة وصيتك المقدسة وأردت أن تجدده وترده إلي رتبته الأولى لا ملاك ولا رئيس ملائكة ولا رئيس آباء ولا نبياً ائتمنته على خلاصنا . بل أنت بغير استحالة تجسدت وتأنست وشابهتنا في كل شيء ما خلا الخطيئة وحدها وصرت لنا وسيطاً لدى الآب، والحاجز المتوسط نقضته والعداوة القديمة هدمتها وأصلحت الأرضيين مع السمائيين، وجعلت الأثنين واحداً، وأكملت التدبير بالجسد وعند صعودك إلي السموات جسدياً إذ ملأت الكل بلاهوتك قلت لتلاميذك ورسلك القديسين سلامى أعطيكم سلامى أنا أترك لكم، هذا أيضاً الآن أنعم به علينا يا سيدنا طهرنا من كل دنس، ومن كل غش، ومن كل رياء، ومن كل شر، ومن كل مكيدة، ومن تذكار الشر الملبس الموت.",
                cop_cop: "",
                ar_de: "",
                cop_ar: "",
            },
            {
                id: 6,
                speaker: "Diakon",
                cop_de: "",
                de: "Betet für den vollkommenen Frieden, für die Liebe und die apostolischen reinen Küsse.",
                ar: "صلوا من أجل السلام الكامل والمحبة والقبلة الطاهرة الرسولية",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إبروس افكصاستيه إي برتيس تيه لياس إيرينيس كيه آغابيس كيه طون آجيون إسباسمون طون أبوسطولون",
            },
            {
                id: 7,
                speaker: "Volk",
                cop_de: "",
                de: "Herr erbarme dich",
                ar: "يارب ارحم ",
                cop_cop: "",
                ar_de: "",
                cop_ar: "كيريه ليسون",
            },
            {
                id: 8,
                speaker: "Priester",
                cop_de: "",
                de: "Mach uns  alle würdig, o Herr , einander mit  einem reinen Kuss zu grüßen Damit wir ,ohne uns Verurteilung einzuhandeln,  deine unsterblichen und himmlischen Gaben erlangen durch deine Gnade und das Wohlgefallen deines guten Vaters und das Wirken deines heiligen Geistes, denn du bist Versorgen und Spender aller Güter",
                ar: "واجعلنا مستحقين كلنا يا سيدنا أن نقبل بعضنا بعضاً بقبلة طاهرة، لنتناول بغير انطراح في الحكم من موهبتك غير المائتة السمائية، بنعمتك ومسرة أبيك الصالح وفعل روحك القدوس، لأنك أنت الرازق ومُعطى جميع الخيرات.",
                cop_cop: "",
                ar_de: "",
                cop_ar: "",
            },
            {
                id: 9,
                speaker: "Diakon",
                cop_de: "",
                de: "Küsst einander mit einem heiligen Kuss. (Herr erbarme Dich)* 3 Ja o Herr Jesus Christus, Sohn Gottes, erhöre uns und erbarme Dich unser. Tretet heran nach der Vorschrift, steht in Ehrfurcht und schaut nach Osten. Wir hören.",
                ar: ".قبلوا بعضكم بعضاً بقبلةٍ مقدسة. (يارب ارحم)* ۳ نعم يارب الذي هو يسوع المسيح ابن الله الحي، اسمعنا وارحمنا. تقدموا تقدموا تقدموا على الرسم، قفوا برعدة، والي الشرق أنظروا. ننصت",
                cop_cop: "",
                ar_de: "",
                cop_ar: "أسـپـاذسـتي ألليلوس إن فـيلـيـمـاتی  آجـيو. (كيريي إليسوس) * ۳ نای كيريي إيتي فای پي إيسـوس پي إخـرسـتـوس إبشير إم إفنوتى سوتيم إيرون أووه ناي نان. إبروسفرين كاطا إطربو إستـاثيتي كـاطـا إطرومـوايس أناطولاس إفليـبساتـي إبروس خـومين. ",
            },
            {
                id: 10,
                speaker: "Volk",
                cop_de: "",
                de: "Durch die Fürsprachen der Mutter Gottes, der Heiligen Maria, vergib uns, o Herr, unsere Sünden durch Deine Gnade.Wir beten dich an, o Christus, zusammen mit deinem guten Vater, und dem Heiligen Geist,denn du bist (auferstanden/gekommen) und hast uns erlöst. Erbarmen des Friedens, Opfer des Lobes ",
                ar: "بشفاعات والدة الإله القديسة مريم يارب انعم لنا بمغفرة خطايانا نسجد لك أيها المسيح مع أبيك الصالح والروح القدس لأنك (أتيت/قُمت) وخلصتنا رحمة السلام ذبيحة التسبيح",
                cop_cop: "",
                ar_de: "",
                cop_ar: "هيتين نيه إبريسفيا إنتيه تى ثيه أوطوكوس إثؤواب ماريا: إبتشويس آرى إهموت نان إمبى كو إيفول إنتيه نين نوفي. تين أوأوشت إمموك أو بخرستوس: نيم بيك يوت إن آغاثوس: جيه (آك إي/أكطونك) أكسوتي إممون: إيه ليه أوس إيرينيس ثي سيا إيه نيه ثيه أوس",
            },
            {
                id: 11,
                speaker: "",
                cop_de: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_ar: "",
            },
        ],
    },

    // --- CYRILLUS LITURGIE (Kerollosy) ---
    kerollosy: {
        title: {
            de: "Die Liturgie des Hl. Cyrillus",
            ar: "القداس الكيرلسي",
        },
        content: [
            {
                id: 1,
                speaker: "Priester",
                cop_ar: "",
                de: "Betet",
                ar: "صلوا",
                cop_cop: "; Sl/l",
                ar_de: "",
                cop_de: "إشلـــــــيل",
            },
            {
                id: 2,
                speaker: "Diakon",
                cop_ar: "",
                de: "Erhebt euch zum Gebet",
                ar: "للصلاة قفوا",
                cop_cop: "",
                ar_de: "",
                cop_de: "إيه بى إبروس إفشى إسطاثى تيه",
            },
            {
                id: 3,
                speaker: "Priester",
                cop_ar: "",
                de: "Der Friede seit mit allen",
                ar: "السلام لجميعكم",
                cop_cop: "",
                ar_de: "",
                cop_de: "إيرينى باسى",
            },
            {
                id: 4,
                speaker: "Volk",
                cop_ar: "",
                de: "Und mit deinem Geiste",
                ar: "ولروحك أيضا",
                cop_cop: "",
                ar_de: "",
                cop_de: "كيه طو إبنفماتى سو",
            },
            {
                id: 5,
                speaker: "Priester",
                cop_ar: "",
                de: "O Urheber des Lebens , König der Ewigkeiten Gott, vor dem jedes Knie  sich beugt im Himmel und auf Erden und unter der Erde! Vor dem alle sich neigen und unterwerfen mit dem Joch der Sklaverei unter die Macht des Zepters seines Königtums! Er, den die Heerscharen der Engel, die himmlischen Ränge und die Geistwesen verherrlichen mit einer Stimme ohne Unterlass seine Göttlichkeit aussprechend. Es gefällt dir, dass wir schwache Irdische dir dienen, nicht wegen der Reinheit unserer Hände, denn wir haben das Rechte auf Erden nicht getan, sondern weil es dein Willen ist, uns Elenden und Unwürdigen von deiner Reinheit zu geben. Nimm uns auf zu dir, o gütiger Menschenliebender, denn wir nähern uns deinem heiligen Altar nach deiner Gnade. Mache uns deines himmlischen Friedens würdig, der deiner Göttlichkeit entspricht und voller Erlösung ist, damit wir ihn uns gegenseitig in vollkommener Liebe geben und einander mit einem heiligen Kuss küssen.",
                ar: "یا رئيس الحياة وملك الدهور، اللهم الذي تجثو له كل ركبة ما في السـمـوات ومـا على الأرض ومـا تحت الأرض، الذى الكل مـذلول وخاضع بعتق العبـودية تحت خـضـوع قضيب ملكه، الذي تمجـده لأجناد الملائكية، والطغمات السمائية، والطبائع العقلية، بصوت لا يسكت ناطق بألوهيته. وإِذ سررت بنا نحن أيضا الضعفاء الأرضيين أن نخدمك، لا من أجل نقاوة أيدينا، لأننا لم نفعل الصلاح على الأرض، بل مريداً أن تعطينا نحن البائسين غير المستحـقين من طهرك، اقبلنا ليك أيها الصالح مـحب البشر إذ ندنو من مـذبحك المقدس ككثرة رحمتك. واجعلنا أهلاً للسلام السمائي اللائق بلاهوتك والمملوء خلاصاً، لنعطيه بعضنا لبعض بمحبة كاملة، ونقبل بعضنا بعضاً بقبلة مقدسة. ",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 6,
                speaker: "Diakon",
                cop_ar: "",
                de: "Betet für den vollkommenen Frieden, für die Liebe und die apostolischen reinen Küsse.",
                ar: "صلوا من أجل السلام الكامل والمحبة والقبلة الطاهرة الرسولية",
                cop_cop: "",
                ar_de: "",
                cop_de: "إبروس افكصاستيه إي برتيس تيه لياس إيرينيس كيه آغابيس كيه طون آجيون إسباسمون طون أبوسطولون",
            },
            {
                id: 7,
                speaker: "Volk",
                cop_ar: "",
                de: "Herr erbarme dich",
                ar: "يارب ارحم ",
                cop_cop: "",
                ar_de: "",
                cop_de: "كيريه ليسون",
            },
            {
                id: 8,
                speaker: "Priester",
                cop_ar: "",
                de: "Nicht aus niedriger Gesinnung, die dir Ehrfurcht verweigert, nicht mit trügerischen Gedanken voll bösen Verrats, ohne dass unser Willen mit Boshaftigkeit übereinstimmt,  sondern aus dem Wunsch unserer Seelen und dem Jubel unserer Herzen, weil wir das große vollkommene Zeichen, das der Liebe deines einziges Sohnes gehört, erhalten haben. Weise uns, deine Diener, wegen des Makels unserer Sünden nicht zurück, weil du als Schöpfer unserer Natur weißt, daß kein von einer Frau Geborener vor dir gerechtfertigt ist. Mache uns also bereit, o Herr, mit reinem Herzen und mit von deiner Gnade erfüllter Seele vor dir zu stehen und dieses heilige, lebendige, geistige und unblutige Opfer  darzubringen zum Nachlass unserer Sünden und zur Vergebung der Unwissenheit deines Volkes, denn du bist ein gnädiger und barmherziger Gott.",
                ar: "لا بحاسة مرذولة رافضة لمخافتك. ولا بفكر غاش مملوء من شر الخائن، غير متفقة نياتنا في الخبث، بل برغبة أنفسنا وتهليل قلوبنا، إذ لنا العلامة العظيمة الكاملة التي لمحبة ابنك الوحيد ولا تطرحنا نحن عبيدك من أجل دنس خطايانا، لأنك أنت العارف كخالق جبلتنا أنه ليس مولود إمرأة يتزكي أمامك. فأجعلنا إذاً أهلا يا سيدنا بقلب طاهر ونفس مملوءة من نعمتك أن نقف أمامك ونقدم لك هذه الصعيدة المقدسة الناطقة الروحانية غير الدموية صفحاً لزلاتنا وغفراناً لجهالات شعبك لأنك أنت إله رؤوف متحنن.",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 9,
                speaker: "Diakon",
                cop_ar: "",
                de: "Küsst einander mit einem heiligen Kuss. (Herr erbarme Dich)* 3 Ja o Herr Jesus Christus, Sohn Gottes, erhöre uns und erbarme Dich unser. Tretet heran nach der Vorschrift, steht in Ehrfurcht und schaut nach Osten. Wir hören.",
                ar: ".قبلوا بعضكم بعضاً بقبلةٍ مقدسة. (يارب ارحم)* ۳ نعم يارب الذي هو يسوع المسيح ابن الله الحي، اسمعنا وارحمنا. تقدموا تقدموا تقدموا على الرسم، قفوا برعدة، والي الشرق أنظروا. ننصت",
                cop_cop: "",
                ar_de: "",
                cop_de:
                    "أسـپـاذسـتي ألليلوس إن فـيلـيـمـاتی  آجـيو. (كيريي إليسوس) * ۳ نای كيريي إيتي فای پي إيسـوس پي إخـرسـتـوس إبشير إم إفنوتى سوتيم إيرون أووه ناي نان. إبروسفرين كاطا إطربو إستـاثيتي كـاطـا إطرومـوايس أناطولاس إفليـبساتـي إبروس خـومين. ",
            },
            {
                id: 10,
                speaker: "Volk",
                cop_ar: "",
                de: "Durch die Fürsprache der Mutter Gottes, der Heiligen Maria, vergib uns, o Herr, unsere Sünden durch Deine Gnade.Wir beten dich an, o Christus, zusammen mit deinem guten Vater, und dem Heiligen Geist,denn du bist (auferstanden/gekommen) und hast uns erlöst. Erbarmen des Friedens, Opfer des Lobes ",
                ar: "بشفاعات والدة الإله القديسة مريم يارب انعم لنا بمغفرة خطايانا نسجد لك أيها المسيح مع أبيك الصالح والروح القدس لأنك (أتيت/قُمت) وخلصتنا رحمة السلام ذبيحة التسبيح",
                cop_cop: "",
                ar_de: "",
                cop_de:
                    "هيتين نيه إبريسفيا إنتيه تى ثيه أوطوكوس إثؤواب ماريا: إبتشويس آرى إهموت نان إمبى كو إيفول إنتيه نين نوفي. تين أوأوشت إمموك أو بخرستوس: نيم بيك يوت إن آغاثوس: جيه (آك إي/أكطونك) أكسوتي إممون: إيه ليه أوس إيرينيس ثي سيا إيه نيه ثيه أوس",
            },
            {
                id: 11,
                speaker: "Priester",
                cop_ar: "",
                de: "Der Herr sei mit euch allen",
                ar: "الرب مع جميعكم.",
                cop_cop: "",
                ar_de: "",
                cop_de: "أوكيريوس ميه طا بانضون إممون",
            },
            {
                id: 12,
                speaker: "Volk",
                cop_ar: "",
                de: "Und mit deinem Geiste",
                ar: "ومع روحك أيضاً",
                cop_cop: "",
                ar_de: "",
                cop_de: "كيه ميه طا طو إبنفما طوسو",
            },
            {
                id: 13,
                speaker: "Priester",
                cop_ar: "",
                de: "Erhebt Eure Herzen !",
                ar: "إرفعوا قلوبكم",
                cop_cop: "",
                ar_de: "",
                cop_de: "آنو إيمون طاذكارذياس",
            },
            {
                id: 14,
                speaker: "Volk",
                cop_ar: "",
                de: "Wir haben sie beim Herrn",
                ar: "هي عند الرب",
                cop_cop: "",
                ar_de: "",
                cop_de: "إيه خومين إبروس طون كيريون",
            },
            {
                id: 15,
                speaker: "Priester",
                cop_ar: "",
                de: "Lasst uns dem Herrn danken",
                ar: "فلنشكر الرب",
                cop_cop: "",
                ar_de: "",
                cop_de: "إيفخاريستى صومين طو كيريو",
            },
            {
                id: 16,
                speaker: "Volk",
                cop_ar: "",
                de: "Würdig und recht",
                ar: "مستحق وعادل",
                cop_cop: "",
                ar_de: "",
                cop_de: "أكسيون كيه ذى كيه أون",
            },
            {
                id: 17,
                speaker: "Priester",
                cop_ar: "",
                de: "Würdig und recht, würdig und recht, würdig und recht: Es ist in Wahrheit würdig und recht, heilig, angemessen und nützlich für unsere Seelen, unsere Leiber und unseren Geist! Der du bist, Meister, Herr, Gott, Vater, Allmächtiger ! Zu jeder Zeit und an jedem Ort deiner Herrschaft, oben wir dich, preisen wir dich, segnen wir dich, dienen wir dir, beten wir dich an, danken dir und verherrlichen dich. Und wir bekennen uns vor dir Tag und Nacht mit nie ruhenden Lippen, mit unruhigen Herzen und mit Lobpreis ohne Unterlass. Du bist es, der die Himmel geschaffen hat und was in den Himmeln ist, die Erde und was auf ihr ist, die Meere, Flüsse, Wasserquellen und Seen und alles was darin ist Du bist es, der den Menschen nach deinem Bild und dir ähnlich erschaffen und alle übrigen Dinge durch deine Weisheit geschaffen hat, durch dein wahres Licht, dein eingeborener Sohn, unser Herr, Gott, Erlöser und unser aller König, Jesus Christus, durch den wir danken und dir mit ihm und dem Heiligen Geist, der Heiligen Dreifaltigkeit, die eines Wesens und untrennbar ist, dieses lebendige Opfer darbringen und diesen unblutigen Dienst verrichten. Dieses, was alle Völkerschaften dir darbringen! Vom Osten zum Westen und vom Norden zum Süden. Denn dein Name, o Herr, ist groß vor allen Völkerschaften, und an jedem Ort werden deinem heiligen Namen Räucherwerk und reine Opfer wie diese Opfergabe und Gabe dargebracht. ",
                ar: "مستحق وعادل مستحق وعادل مستحق وعادل لأنه بالحقيقة  مستحق وعادل ومقدس ولائق ونافع لنفوسنا واجسادنا وارواحنا ايها الكائن السيد الرب الله الآب ضابط الكل في كل زمان وبكل مكان لربوبيتك أن نسبحك ونرتل لك ونباركك ونخدمك ونسجد لك ونشكرك ونمجدك. ونعترف لك ليلاً ونهاراً بشفاه غير هادئة وقلب لا يسكت وتمجيدات لا تنقطع.انت الذي خلقت السموات وما في السموات والأرض وكل ما فيها البحار والأنهار والينابيع والبحيرات وما في جميعها.انت هو الذي خلقت الانسان كصورتك وكشبهك وخلقت كل الاشياء بحكمتك نورك الحقيقي ابنك الوحيد ربنا والهنا ومخلصنا وملكنا كلنا يسوع المسيح هذا الذي من قبلة نشكر ونقرب لك معه ومع الروح القدس الثالوث المقدس المساوي غير المفترق هذه الذبيحة الناطقة وهذه الخدمة غير الدموية. هي التي تقربها لك جميع الأمم. من مشارق الشمس الي مغاربها ومن الشمال الي الجنوب لأن اسمك عظيم يارب في جميع الامم وفي كل مكان يقدم بخور لاسمك القدوس وصعيدة طاهره وعلي هذه الذبيحة وهذا القربان.",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 18,
                speaker: "Diakon",
                cop_ar: "",
                de: "Wer sitzt, stehe auf!",
                ar: "أيها الجلوس قفوا",
                cop_cop: "",
                ar_de: "",
                cop_de: "إي كاثي ميه ني أناسثيتيه",
            },
            {
                id: 19,
                speaker: "Priester",
                cop_ar: "",
                de: "Denn dein Name, o Herr, ist groß vor allen Völkerschaften, und an jedem Ort werden deinem heiligen Namen Räucherwerk und reine Opfer wie diese Opfergabe und Gabe dargebracht. und über jedem Namen, der genannt werden wird, nicht nur in dieser Zeit, sondern auch in der zukünftigen Welt.",
                ar: "لأنك انت هو الذي فوق كل رئاسة وكل سلطان وكل قوة وكل سيادة وكل اسم يسمي ليس في هذا الدهر فقط بل وفي الآتي.",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 20,
                speaker: "Diakon",
                cop_ar: "",
                de: "Schaut nach Osten!",
                ar: "وإلى الشرق انظروا",
                cop_cop: "",
                ar_de: "",
                cop_de: "إس أناطولاس إفليب صاتيه",
            },
            {
                id: 21,
                speaker: "Priester",
                cop_ar: "",
                de: "Du bist es, vor dem abertausende und aber zehntausende Engel, Erzengel und die Heiligen stehen und dienen. Du bist es, vor dem deine beiden guten Wesen stehen, die sechs Flügel und viele Augen haben, die Seraphim und Cherubim. ",
                ar: "أنت الذي يقوم أمامك ألوف ألوف وربوات ربوات الملائكة ورؤساء الملائكة المقدسين يخدمونك. انت الذي يقوم أمامك الكائنات الكريمان جداً ذو الستة الأجنحه الكثيرا الاعين السيرافيم والشاروبيم. فبجناحين يغطون وجوههم من اجل لاهوتك الذي لا يستطاع النظر إليه ولا التفكر فيه. وباثنين يغطون أرجلهم ويطيرون بالاثنين الآخرين.لأن في كل زمان يقدسك كل أحد. لكن مع كل من يقدسك اقبل تقديسنا منا نحن أيضاً يارب إذ نسبحك معهم قائلين",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 22,
                speaker: "Volk",
                cop_ar: "",
                de: "Heilig, heilig, heilig ist der Herr der Heerscharen , der Himmel und die Erde sind erfüllt von deiner heiligen Herrlichkeit",
                ar: "قدوس قدوس قدوس رب الصاباؤوت السماء والأرض مملوءتان من مجدك الأقدس",
                cop_cop: "",
                ar_de: "",
                cop_de: "جيه آجيوس آجيوس آجيوس كيريوس صافاؤوت: إبلى ريس أو أورانس كيه إى جى تيس آجياس صوذوكسيس",
            },
            {
                id: 23,
                speaker: "Priester",
                cop_ar: "",
                de: "Heilig Heilig Heilig",
                ar: "قدوس، قدوس، قدوس",
                cop_cop: "",
                ar_de: "",
                cop_de: "آجيوس، آجيوس، آجيوس",
            },
            {
                id: 24,
                speaker: "Priester",
                cop_ar: "",
                de: "Heilig bist du Herr der Heerscharen, der Himmel und die Erde sind erfüllt von deiner heiligen Herrlichkeit. O Herr, unser Gott, der Himmel und die Erde sind wahrhaftig erfüllt von deiner heiligen Herrlichkeit, durch deinen eingeborenen Sohn, unseren Herrn, Gott, Erlöser und unser aller König Jesus Christus: Erfülle diese Opfergabe, die dir gehört, o Herr, mit dem Segen, der von dir ist. Durch die Herabkunft deines Heiligen Geistes auf sie. ",
                ar: "قدوس رب الجنود السماء والأرض مملوءتان من مجدك الأقدس، أيها الرب الهنا بالحقيقه السماء والارض مملوءتان من مجدك الأقدس، من قبل ابنك الوحيد ربنا والهنا ومخلصنا وملكنا يسوع المسيح املأ هذه الصعيدة التي لك يارب بالبركة التي من قبلك. بحلول روحك القدوس عليها",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 25,
                speaker: "Volk",
                cop_ar: "",
                de: "Amen",
                ar: "آميــــن",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 26,
                speaker: "Priester",
                cop_ar: "",
                de: "Mit dem Segen segne sie",
                ar: "وبالبركة بارك",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 27,
                speaker: "Volk",
                cop_ar: "",
                de: "Amen",
                ar: "آميــــن",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 28,
                speaker: "Priester",
                cop_ar: "",
                de: "Und mit der Heiligung heilige sie",
                ar: "وبالتقديس قدس",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 29,
                speaker: "Volk",
                cop_ar: "",
                de: "Amen",
                ar: "آميــــن",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 30,
                speaker: "Priester",
                cop_ar: "",
                de: "Diese deine heiligen Opfergaben, die wir begonnen haben, vor dich zu legen, dieses Brot und diesen Kelch. Denn dein einziger Sohn, unser Herr, Gott und Erlöser und unser aller König Jesus Christus! In der Nacht, in der er sich selbst hingab, um für unsere Sünden zu leiden und auch den Tod, den er aus sich selbst aus seinem eigenen Willen für uns alle annahm",
                ar: "قرابينك هذه المكرمة التي بدأنا بوضعها أمامك هذا الخبز وهذه الكأس لأن ابنك الوحيد ربنا والهنا ومخلصنا وملكنا كلنا يسوع المسيح. في الليلة التي اسلم ذاته فيها ليتألم عن خطايانا والموت الذي قبله بذاته بإرادته وحده عنا كلنا.",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 31,
                speaker: "Volk",
                cop_ar: "",
                de: "Wir glauben",
                ar: "نؤمــــــن",
                cop_cop: "",
                ar_de: "",
                cop_de: "بيستيف أومين",
            },
            {
                id: 32,
                speaker: "Priester",
                cop_ar: "",
                de: "Er nahm Brot in seine reinen, makellosen, unbefleckten, seligen und lebensspendenden Hände.",
                ar: "أخذ خبزاً على يديه الطاهرتين اللتين بلا عيب ولا دنس الطوباويتين المحييتين",
                cop_cop: "",
                ar_de: "",
                cop_de: "أفتشي إن أو أويك إيجين نيف جيج إثؤواف إن آتتشنى أووه إن أتثوليف أووه إم مكاريون أووه أنريف تنخو",
            },
            {
                id: 33,
                speaker: "Volk",
                cop_ar: "",
                de: "Wir glauben, dass dieses in Wahrheit so ist. Amen.",
                ar: "نؤمن أن هذا هو بالحقيقة: أمين.",
                cop_cop: "",
                ar_de: "",
                cop_de: "تين ناهتى جيه فاى بيه خين أو ميثمى: آمين",
            },
            {
                id: 34,
                speaker: "Priester",
                cop_ar: "",
                de: "Er blickte hinauf zum Himmel zu dir, der sein Vater ist, Gott und Meister eines jeden.",
                ar: "ونظر إلى فوق نحو السماء إليك الله أبيك وسيد كل أحد ",
                cop_cop: "",
                ar_de: "",
                cop_de: "أفجوشت إى إبشوى إى إتفى هاروك فيئتيفوف إنيوت إفنوتى أووه إفنيب إنتى أوؤن نيفين",
            },
            {
                id: 35,
                speaker: "Priester",
                cop_ar: "",
                de: "Er dankte",
                ar: "وشكـر",
                cop_cop: "",
                ar_de: "",
                cop_de: "إيه طاف شيب أهموت",
            },
            {
                id: 36,
                speaker: "Volk",
                cop_ar: "",
                de: "Amen",
                ar: "آميـــــن",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 37,
                speaker: "Priester",
                cop_ar: "",
                de: "Er segnete es",
                ar: "وباركه",
                cop_cop: "",
                ar_de: "",
                cop_de: "أف إسمو إيه روف",
            },
            {
                id: 38,
                speaker: "Volk",
                cop_ar: "",
                de: "Amen",
                ar: "آميـــــن",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 39,
                speaker: "Priester",
                cop_ar: "",
                de: "Und heiligte es",
                ar: "وقدسه",
                cop_cop: "",
                ar_de: "",
                cop_de: "أف إير آجيا زين إمموف",
            },
            {
                id: 40,
                speaker: "Volk",
                cop_ar: "",
                de: "Amen",
                ar: "آميـــــن",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 41,
                speaker: "Volk",
                cop_ar: "",
                de: "Wir glauben, bekennen und verherrlichen",
                ar: "نؤمن ونعترف ونمجد",
                cop_cop: "",
                ar_de: "",
                cop_de: "بستيف أومين كيه أومولوغومين كيه ذوكصازومين",
            },
            {
                id: 42,
                speaker: "Priester",
                cop_ar: "",
                de: "Er teilte und gab es seinen heiligen, ehrwürdigen Jüngern und reinen Aposteln und sprach: Nehmt, esst alle davon, denn dies ist mein Leib, der für euch und für viele gebrochen wird zur Vergebung der Sünden. Tut dies zu meinem Gedächtnis",
                ar: "وقسمه وأعطاه لتلاميذه المكرمين  القديسين ورسله الأطهار قائلاً: خذوا كلوا منه كلكم، لأن هذا هو جسدي. الذي يقسم عنكم وعن كثيرين يعطى لمغفرة الخطايا  هذا اصنعوه لذكرى",
                cop_cop: "",
                ar_de: "",
                cop_de: "آف فشف أفتيف إننى إيتي نوف إن أجيوس إم ماثيتيس أووه إن أبو سطولوس إثؤواب إفجو إمموس جى تشى أؤوم إيفول إنخيتف تيرو فاى غار بى باسوما إتونافشف  إيجين ثينو نيم هان كى ميش إنسى تيف إى إبكو إيفول انتى نى نوفى فاى أريتف إيبا إير افميفى",
            },
            {
                id: 43,
                speaker: "Volk",
                cop_ar: "",
                de: "Dies ist es in Wahrheit. Amen",
                ar: "هذا هو بالحقيقة: آمين",
                cop_cop: "",
                ar_de: "",
                cop_de: "فاى بيه خين أوميثمي: آمين",
            },
            {
                id: 44,
                speaker: "Priester",
                cop_ar: "",
                de: "Ebenso nahm er nach dem Mahl den Kelch, mischte Wein und Wasser",
                ar: "وهكذا الكأس أيضاً  من بعد العشاء مزجها من ثمرة الكرمة وماء",
                cop_cop: "",
                ar_de: "",
                cop_de: "باى ريتى أون بى كى أفوت مينينسا بى ذيبنون أفثوطف إيفول خين أو إرب نيم أو موؤو",
            },
            {
                id: 45,
                speaker: "Priester",
                cop_ar: "",
                de: "Er dankte",
                ar: "وشكـر",
                cop_cop: "",
                ar_de: "",
                cop_de: "إيه طاف شيب أهموت",
            },
            {
                id: 46,
                speaker: "Volk",
                cop_ar: "",
                de: "Amen",
                ar: "آميـــــن",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 47,
                speaker: "Priester",
                cop_ar: "",
                de: "Er segnete es",
                ar: "وباركه",
                cop_cop: "",
                ar_de: "",
                cop_de: "أف إسمو إيه روف",
            },
            {
                id: 48,
                speaker: "Volk",
                cop_ar: "",
                de: "Amen",
                ar: "آميـــــن",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 49,
                speaker: "Priester",
                cop_ar: "",
                de: "Und heiligte es",
                ar: "وقدسه",
                cop_cop: "",
                ar_de: "",
                cop_de: "أف إير آجيا زين إمموف",
            },
            {
                id: 50,
                speaker: "Volk",
                cop_ar: "",
                de: "Amen",
                ar: "آميـــــن",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 51,
                speaker: "Volk",
                cop_ar: "",
                de: "Wiederum glauben, bekennen und verherrlichen wir",
                ar: "وأيضاً نؤمن ونعترف ونمجد",
                cop_cop: "",
                ar_de: "",
                cop_de: "كيه بالين بستيف أومين كيه أومولوغومين كيه ذوكصازومين",
            },
            {
                id: 52,
                speaker: "Priester",
                cop_ar: "",
                de: "Er kostete davon und gab ihn seinen heiligen, ehrwürdigen Jüngern und reinen Aposteln mit den Worten: Nehmt, trinkt alle daraus, denn dies ist mein Blut des neuen Bundes, das für euch und für viele vergossen wird und hingegeben zur Vergebung der Sünden. „Tut dies zu meinem Gedächtnis“.",
                ar: "وذاق وأعطاها أيضاً لتلاميذه المكرمين القديسين ورسله الأطهار قائلاً: خذوا اشربوا منها كلكم لأن هذا هو دمى الذي للعهد الجديد الذى يسفك عنكم وعن كثيرين يعطى لمغفرة الخطايا هذا اصنعوه لذكري",
                cop_cop: "",
                ar_de: "",
                cop_de: "آف جيمتيبى أف تيف أون إنى إيتينوف إن أجيوس إم ماثيتيس أووه إن ابسطولوس اثؤواف إفجو إمموس جى تشى سو إيفول إنخيتف تيرو فاى غار بى باإسنوف إنتى تى ذياثيكى إمفيري إيطو نافونف إيفول إبجين ثينو نيم هان كى ميش انسيتيف إى إبكو ايفول انتى نى نوفى فاى أريتف إيبا إير افميفئ",
            },
            {
                id: 53,
                speaker: "Volk",
                cop_ar: "",
                de: "Dies ist es auch in Wahrheit. Amen",
                ar: "وهذا هو أيضاً بالحقيقة آمين",
                cop_cop: "",
                ar_de: "",
                cop_de: "فاى أون بى خين أو ميثمي آمين",
            },
            {
                id: 54,
                speaker: "Priester",
                cop_ar: "",
                de: "Denn jedes Mal, wenn ihr von diesem Brot esst, und aus diesem Kelch trinkt, verkündet ihr meinen Tod, bekennt meine Auferstehung und erinnert euch meiner, bis ich wieder komme.",
                ar: "لأن كل مرة تأكلون من هذا الخبز وتشربون من هذه الكأس تبشرون بموتي وتعترفون بقيامتي وتذكروني إلى أن أجئ ",
                cop_cop: "",
                ar_de: "",
                cop_de: "سوب غار نيفين إيتين نا أو أوم إيفول خين باى أو يك فاى أووه إنتى تين سو إيفول خين باى أفوت فاى إيرييتين هى أو يش إمبامو إيرتين إير أمولوجين إنتا أناسطاسيس إيرى تين إيرى إمباميفئي شاتى إى",
            },
            {
                id: 55,
                speaker: "Volk",
                cop_ar: "",
                de: "Amen, Amen, Amen, deinen Tod, o Herr, verkünden wir, deine heilige Auferstehung und deine Himmelfahrt bekennen wir. Wir loben dich, wir preisen dich, wir danken dir, o Herr, und wir bitten dich, unser Gott!",
                ar: " امين امين امين بموتك يارب نبشر وبقيامتك المقدسة وصعودك إلى السموات نعترف نسبحُك نباركُك نشكرُك يارب ونتضرعُ إليكَ يا إلَهنا.",
                cop_cop: "",
                ar_de: "",
                cop_de: "آمين آمين آمين طون ثاناطون صو كيريه كاطانجيه لومين: كيه تين آجيان صو آناسطاسين: كيه تين أناليبسين صو إنتيس أورانيس سيه أومولوغومين: سيه إيه نومين سيه إفلوغومين سيه إفخاريس طومين كيريه: كيه ذيه أو ميه طا سو أوثيه أوس إيمون",
            },
            {
                id: 56,
                speaker: "",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },




        ],
    },
}