// src/liturgyData.js

import { title } from "framer-motion/client";
// NEU: Übersetzungen für die Benutzeroberfläche (UI)
export const uiTranslations = {
    titles: {
        homeSubtitle: {
            de: "Kirche der Hl. Maria & Hl.Philopater Mercurius Unna-Massen",
            ar: "كنيسه العدرا و الشهيد ابي سيفين القبطيه الارثذوكسيه باونا ماسن"
        },
        chooseLiturgy: {
            de: "Wähle die Liturgie",
            ar: "اختر القداس"
        },
        settings: {
            de: "Einstellungen",
            ar: "الإعدادات"
        },
        appLanguage: {
            de: "App Sprache / لغة التطبيق",
            ar: "لغة التطبيق / App Sprache"
        },
        prayerLanguages: {
            de: "Gebetssprachen (Max 3)",
            ar: "لغات الصلاة (بحد أقصى 3)"
        },
        loading: {
            de: "Wird geladen...",
            ar: "جار التحميل..."
        },
        done: {
            de: "Fertig",
            ar: "تم"
        }
    },
    buttons: {
        agpeya: { de: "Agpeya", ar: "الأجبية" },
        liturgy: { de: "Liturgie", ar: "القداسات" },
        bible: { de: "Bibel", ar: "الكتاب المقدس" },
        offering: { de: "Auswahl des Lammbrotes", ar: "الحمل" },
        basily: { de: "Basilius ", ar: "القداس الباسيلي" },
        kerollosy: { de: "Cyrillus ", ar: "القداس الكيرلسي" },
        gregorios: { de: "Gregorios ", ar: "القداس الغريغوري" },
        habashy: { de: "Äthiopisch ", ar: "القداس الحبشي" }
    }
};
// src/liturgyData.js

/* ... (uiTranslations bleiben gleich) ... */

export const languages = {
    de: { label: "Deutsch", default: true },
    ar: { label: "عربي / Arabisch", default: true },

    // Deine anderen Sprachen 
    ar_de: { label: "Franco / فرانكو", default: false },
    cop_ar: { label: "Koptisch (Arabisch) / قبطي معرب", default: true },
    cop_de: { label: "Koptisch Franco / قبطي فرانكو", default: false },
    cop_cop: { label: "Koptisch / قبطي", default: false },
};



export const liturgies = {
    offering: {
        title: {
            de: "Auswahl des Lammbrotes",
            ar: "تقديم الحمل"
        },
        content: [
            // 1. GLAUBENSBEKENNTNIS
            {
                id: 1,
                speaker: "Volk",
                de: "Wir glauben an den einen Gott: Gott den Vater , den Allmächtigen, Schöpfer des Himmels und der Erde, alles Sichtbaren und Unsichtbaren.Wir glauben an den einen Herrn Jesus Christus , Gottes einzigen Sohn, geboren aus dem Vater vor aller Zeit Licht vom Lichte , wahrer Gott vom wahren Gott, gezeugt, nicht geschaffen, eines Wesens mit dem Vater; durch ihn ist alles geworden. , nicht geschaffen, eines Wesens mit dem Vater; durch ihn ist alles geworden.  Für uns Menschen und um unseres Heils willen ist er vom Himmel herabgestiegen. Er hat Fleisch angenommen durch den Heiligen Geist, von der Jungfrau Maria und ist Mensch geworden. Er wurde gekreuzigt unter Pontius Pilatus an unserer Statt,hat gelitten und ist begraben worden.Am dritten Tag auferstanden von den Toten gemäß der Schrift,aufgefahren in den Himmel, sitzt er zur Rechten seines Vaters Und so wird er wiederkommen in seiner Herrlichkeit, zu richten die Lebenden und die Toten, und seiner Herrschaft wird kein Ende sein.Ja, wir glauben an den Heiligen Geist, der Herr ist und lebendig macht, der aus dem Vater hervorgeht , der mit dem Vater und dem Sohn angebetet und verherrlicht wird. Er hat gesprochen durch die Propheten Wir glauben an die eine heilige, universale und apostolische Kirche. Wir bekennen die eine Taufe zur Vergebung der Sünden. Wir erwarten die Auferstehung der Toten und das Leben der kommenden Welt. Amen.",
                ar: "بالحقيقة نؤمن بإله واحد الله الآب ضابط الكل خالق السماء والأرض ما يُرى وما لا يُرى نؤمن برب واحد يسوع المسيح ابن الله الوحيد المولود من الآب قبل كل الدهور نور من نور إله حق من إله حق مولود غير مخلوق ، مساوٍ للآب فى الجوهـر الذى به كان كل شيء هذا الذى من أجلنا نحن البشر ومن أجل خلاصنا نزل من السماء وتجسد من الروح القدس ومن مريم العذراء وتأنس وصلب عنا على عهد بيلاطس البنطي تألم وقبر وقام من بين الاموات فى اليوم الثالث كما فى الكتب وصعد الى السموات وجلس عن يمين أبيه وأيضاً يأتى فى مجده ليدين الاحياء والاموات الذى ليس لملكه انقضاء نعم نؤمن بالروح القدس الرب المحيي المنبثق من الآب. نسجد له ونمجده مع الآب والابن الناطق فى الأنبياء وبكنيسة واحدة مقدسة جامعة رسولية ونعترف بمعمودية واحدة لمغفرة الخطايا وننتظر قيامة الأموات وحياة الدهر الآتى .آمين",
                ar_de: "Bel 7aqiqa no2men be elah wa7ed, Allah el Ab dabet el kol, 5aleq el sama wal ard, ma yora wa ma la yora. No2men be rab wa7ed Yassou3 el Massi7, Ebn Allah el wa7id, el mawloud men el Ab qabl kol el dohour. Nour men Nour, Elah 7aq men Elah 7aq, mawloud gheir ma5louq, mosawen lel Ab fel gawhar, allazy bihi kan kol shay2. Haza allazy men aglina na7n el bashar, wa men agl 5alasna, nazal men el sama, wa tagassad men el Ro7 el Qodos wa men Mariam el 3azra2 wa ta2anas. Wa soleb 3anna 3ala 3ahd Bilatos el Bonti, ta2alam wa qober wa qam men bein el amwat fel yom el thaleth kama fel kotob. Wa sa3ad ela el samawat, wa galas 3an yamin abih. Wa aydan ya2ti fi magdehi le yadin el a7ya2 wal amwat, allazy laysa le molkehi enqida2. Na3am no2men bel Ro7 el Qodos, el Rab el mo7yi, el monbathiq men el Ab. Nasgod lahu wa nomagedohu ma3 el Ab wal Ebn, el nateq fel anbya2. Wa be kanisa wa7da moqadasa game3a rasoulya. Wa na3taref be ma3moudia wa7da le maghferet el 5ataya. Wa nantazer qiyamat el amwat, wa 7ayat el dahr el aaty. Amin.",

            },

            // 2. KYRIE (MIT ÜBERSCHRIFT)
            {
                id: 2,
                // Hier ist der Titel für den neuen Abschnitt
                sectionTitle: {
                    de: "Die Auswahl des Lammbrotes",
                    ar: "تقديم الحمل"
                },
                speaker: "Volk",
                // Das \n sorgt für neue Zeilen im Arabischen
                ar: "كيريه ليسون كيريه ليسون يارب ارحم\nكيريه ليسون كيريه ليسون ارحمنا يا الله\nكيريه ليسون كيريه ليسون اسمعنا و ارحمنا",
                cop_cop: "Kurie `ele`ycon.",


            },
            {
                id: 3,
                speaker: "Volk",

                de: "Heilig, heilig, heilig ist der Herr der Heerscharen, der Himmel und die Erde sind erfüllt von deiner Herrlichkeit und Ehre. Gott, Vater, Allmächtiger, erbarme dich unser,Heiligste Dreifaltigkeit, erbarme dich unser,  Herr, Gott aller Mächte und Gewalten, sei mit uns, denn wir haben keinen anderen Beistand in unseren Nöten und Bedrängnissen außer dir. Tilge, vergib und verzeih uns unsere Missetaten, o Gott: die freiwilligen und unfreiwilligen, die bewussten und unbewussten, die sichtbaren und unsichtbaren. Herr, vergib sie uns um deines heiligen Namens willen, der über uns angerufen ist. Nach deinem Erbarmen, o Herr, und nicht nach unseren Sünden.  Unser Herr, mache uns würdig, in Dankbarkeit zu sprechen: Vater unser....",
                ar: " ....قدوس، قدوس، قدوس، رب الصباؤوت. السماء والأرض مملوءتان من مجدك وكرامتك. ارحمنا يا الله الآب ضابط الكل. أيها الثالوث القدوس ارحمنا. أيها الرب إله القوات كن معنا، لأنه ليس لنا معين في شدائدنا وضيقاتنا سواك. حل واغفر واصفح لنا يا الله عن سيئاتنا، التي صنعناها بإرادتنا والتي صنعناها بغير إرادتنا، التي فعلناها بمعرفة والتي فعلناها بغير معرفة، يارب اغفرها لنا من اجل اسمك القدوس الذي دعي علينا. كرحمتك يا رب وليس كخطايانا. و اجعلنا مستحقين ان نقول لك بشكر ابانا الذي ",
                ar_de: "Qoddos, Qoddos, Qoddos, Rab el Saba2out. El sama wal ard mamlou2atan men magdika wa karamatika. Er7amna ya Allah el Ab dabet el kol. Ayuha el thalouth el qoddos er7amna. Ayuha el Rab elah el qowat kon ma3ana, le annahu laysa lana mo3in fi shada2edina wa diqatina siwak. 7al wa eghfer wa esfa7 lana ya Allah 3an saye2atina, allati sana3naha be iradatina wa allati sana3naha be gheir iradatina, allati fa3alnaha be ma3rifa wa allati fa3alnaha be gheir ma3rifa, Ya Rab eghferha lana men agl esmika el qoddos allazy do3ya 3alayna. Ka ra7matika ya Rab wa laysa ka 5atayana. Wa eg3alna mosta7iqqin an naqoul laka be shokr Abana allazy..",



            },
            {
                id: 4,
                speaker: "P",
                cop_ar: "أو أو أو نيم أوطايو أوطايو نيم أو أو أو إنتي بان أجيا ترياس لإفيوت نيم ابشيري نيم بي ابنيفما إثؤواف أو هيرينى نيم و كوت إيجين تي أوى إممافتس إثؤواف إن كاثوليكي إن إبواسطوليكي إن اككلسيا انتي افنوتي آمين أري افمفيئي ابشويس ان ني ايطاف ايني ناك ايخون ان ناي ذورون  نيم ني ايطاف اين ايجوؤو نيم ني ايطاف اينو ايفول هيطوطو موي نؤو تيرو امبي فيكي بي ايفول خين ني فيئوي",
                de: "Ehre und Ruhm, Ruhm und Ehre der heiligen Dreifaltigkeit, dem Vater, dem Sohn und den Heiligen Geist Friede und Wachstum der Kirche Gottes, der einen, einzigen, heiligen, universalen und apostolischen Kirche. Amen Gedenke, o Herr, derer, die dir diese Gaben dargebracht haben, derer, für die sie dargebracht werden und derer, durch die sie dargebracht werden. Gib ihnen allen den himmlischen Lohn ",
                ar: "مجداً وإكراماً إكراماً ومجداً للثالوث الأقدس الآب والابن والروح القدس سلاماً وبنياناً لكنيسة الله الواحدة الوحيدة المقدسة الجامعة الرسولية آمين أذكر يارب الذين قدموا لك هذه القرابين والذين قُدمت عنهم والذين قُدمت بواسطتهم أعطهم كلهم الأجر السمائي ",
                cop_cop: "",
                ar_de: "Magdan wa ekraman, ekraman wa magdan lel thalouth el aqdas, el Ab wal Ebn wal Ro7 el Qodos. Salaman wa bonyanan le kanisat Allah el wa7ida el wa7ida el moqadasa el game3a el rasoulya. Amin. Ozkur ya Rab allazina qadamou laka hazihi el qarabin, wa allazina qodimat 3anhom, wa allazina qodimat be wasitatihim, a3tehom kolahom el agr el sama2i.",
                cop_de: "Ouoh nem outayo outayo nem ouow ente pen agia trias efyot nem epshiri nem pi pnevma ethowab ou hirini nem ou koti egen ti oi emmavets ethowab en katholiki en apostoliki en ekklesia ente efnouti Amin ari efmevi epshois en ni etaf ini nak ekhoun en nai doron nem ni etaf en egou nem ni etaf enou evol hitotou moi no tiro empi veki pi evol khen ni feoui.",

            },
            {
                id: 5,
                speaker: "D",
                cop_ar: "إبروس إفكصاستيه إي بيرطون آجيون تيميون ذورون طوطون كيه سيون ايمون كيه إبروس فيرون طون: كريه ليسون.",
                de: "Betet für diese heiligen und ehrwürdigen Gaben, für unsere Opfer und für diejenigen, die sie dargebracht haben.",
                ar: "صلوا من أجل هذه القرابين المقدسة الكريمة وتقدماتنا والذين قدموها يارب ارحم ",
                cop_cop: "",
                ar_de: "Sallou men agl hazihi el qarabin el moqadasa el karima wa taqdomatina wa allazina qadamouha Ya Rab er7am.",
                cop_de: "Pros evxasthe yper ton agion timion doron touton ke thision imon ke prosferonton: Kyrie eleison.",

            },
            {
                id: 6,
                speaker: "Volk",
                cop_ar: "الليلويا فاى بيه بى إيه هؤو إيه طا إبتشويس ثاميوف: مارين ثليل إنتين أونوف إممون إنخيتف:",
                de: "Halleluja. Dies ist der Tag, den der Herr gemacht hat; Lasst uns jubeln und uns freuen an ihm.",
                ar: "هلليلويا. هذا هو اليوم الذى صنعه الرب فلنفرح ونبتهج فيه",
                cop_cop: "",
                ar_de: "Halelluia. Haza howa el yom allazy sana3ahu el Rab, fal nafra7 wa nabtaheg fihi.",
                cop_de: "Alleluia. Fai pe pi e-ho-oo eta Epchois thamiof, maren thelel enten ounof emmon enkheetf.",
            },
            {
                id: 7,
                speaker: "Priester",
                cop_ar: "خين إفران إم افيوت نيم إبشيري نيم بي إبنيفما إثؤواب أو نوتي إن أو أوت اف أسمارؤوت انجى افيوت بى بانطوكراطور آمين",
                de: "Im Namen des Vaters, des Sohnes und des Heiligen Geistes, des einen Gottes. Gepriesen sei Gott, der Vater, der allmächtige. Amen.",
                ar: "باسم الآب والابن والروح القدس إله واحد مبارك الله الآب ضابط الكل",
                cop_cop: "",
                ar_de: "Basm el Ab wal Ebn wal Ro7 el Qodos elah wa7ed mobarak Allah el Ab dabet el kol.",
                cop_de: "Khen efran em efyot nem epshiri nem pi pnevma ethowab ou nouti en ou ot af esmaroot enje efyot pi pantokrator amin.",
            },
            {
                id: 8,
                speaker: "Diakon",
                de: "Amen.",
                ar: "آمين.",
                cop_cop: "",
            },
            {
                id: 9,
                speaker: "Priester",
                cop_ar: "اف أسمارؤوت انجى بيف مونوجينيس انشيرى ايسوس بيخرستوس بين تشويس آمين",
                de: "Gepriesen sei sein eingeborener Sohn, Jesus Christus, unser Herr. Amen.",
                ar: "مبارك ابنه الوحيد يسوع المسيح ربنا امين",
                cop_cop: "",
                ar_de: "Mobarak ebnohu el wa7id Yassou3 el Massi7 Rabbana Amin.",
                cop_de: "Af esmaroot enje pef monogenes enshiri Isos Pkhristos pen chois amin.",
            },
            {
                id: 10,
                speaker: "Diakon",
                de: "Amen.",
                ar: "آمين.",
                cop_cop: "",
            },
            {
                id: 11,
                speaker: "Priester",
                cop_ar: "اف أسمارؤوت انجى بي بنفما اثؤواب ام باراكليتون آمين",
                de: "Gepriesen sei der Heilige Geist, der Tröster. Amen.",
                ar: "مبارك الروح القدس المعزي آمين",
                cop_cop: "",
                ar_de: "Mobarak el Ro7 el Qodos el Mo3azi Amin.",
                cop_de: "Af esmaroot enje pi pnevma ethowab em parakliton amin.",
            },
            {
                id: 12,
                speaker: "Diakon",
                de: "Amen.",
                ar: "آمين.",
                cop_cop: "",
            },

            {
                id: 13,
                speaker: "Diakon",
                cop_ar: "إسباتير آجيوس إس إيوس آجيوس إن إبنيفما آجيون آمين. إفلوجي طوس كيريوس أوثيه أوس إس طوس إيه أوناس آميـن. ني إيثنوس تيرو إسمو إبتشويس مارو إسمو إيه روف إنجيه ني لاؤس تيرو: جيه آبيف ناي طاجرو إيه إهري إيه جون: أووه تيه ميثمي إنتيه إبتشويس شوب شا إينيه آمين. الليلويا",
                de: "Einer ist der Heilige Vater. Einer ist der Heilige Sohn. Einer ist der Heilige Geist. Amen.Gepriesen sei der Herr, Gott in alle Ewigkeiten. Amen Lobt den Herrn, alle Völkerschaften, lobpreist ihn, alle Völker, denn erstarkt ist sein Erbarmen über uns, und die Wahrheit des Herrn bleibt bis in Ewigkeit. Amen. Halleluja. ",
                ar: "واحدٌ هو الآب القدوس، واحدٌ هو الابن القدوس، واحدٌ هو الروح القدس. آمين. مبارك الرب الإله إلي الأبد. آمين. يا جميع الامم باركوا الرب. ولتباركه جميع الشعوب. لان رحمته ثبتت علينا. و حق الرب يدوم إلي الابد. آمين. هلليلويا.",
                cop_cop: "",
                ar_de: "Wa7ed howa el Ab el Qoddos, wa7ed howa el Ebn el Qoddos, wa7ed howa el Ro7 el Qodos. Amin. Mobarak el Rab el Elah ela el abad. Amin. Ya gamie3 el omam bariko el Rab. Wal tobarikhu gamie3 el sho3oub. Lan ra7matuhu thabatat 3alayna. Wa 7aq el Rab yadoum ela el abad. Amin. Halelluia.",
                cop_de: "Espatir agios es iyos agios en epnevma agion amin. Eflogitos kyrios o theos es tos e-onas amin. Ni ethnos tiro esmou epchois marou esmou e-rof enje ni laos tiro: je a-pef nai tagro e-hri e-gon: owoh ti methmi ente epchois shop sha eneh amin. Alleluia",
            },
            {
                id: 14,
                speaker: "Volk",
                cop_ar: "ذوكصابتري كيه إيو كيه آجيو إبنڤماتي: كيه نين كيه آ إى كيه إسطوس إيه أوناس طون إيه أونون آمين. الليلويا",
                de: "Ehre sei dem Vater und dem Sohn und dem Heiligen Geist, jetzt, alle Zeit und in alle Ewigkeit. Amen. Halleluja.",
                ar: "المجد للآب والابن والروح القدس، الآن وكل اوان وإلي دهر الدهور. آمين. هلليلويا.",
                cop_cop: "",
                ar_de: "El magd lel Ab wal Ebn wal Ro7 el Qodos, el an wa kol awan wa ela dahr el dohour. Amin. Halelluia.",
                cop_de: "zoxa patri ke iyo ke agio pnevmati: ke nyn ke a-ei ke es-tos e-onas ton e-onon amin. Alleluia.",
            },
            {
                id: 15,
                sectionTitle: {
                    de: "Danksagungsgebet",
                    ar: "صلاه الشكر"
                },
                speaker: "Priester",
                cop_ar: "إشليل.",
                de: "Betet.",
                ar: "صل.",
                cop_cop: "",
                ar_de: "Salli.",
                cop_de: "Eshlil.",
            },
            {
                id: 16,
                speaker: "Diakon",
                cop_ar: "إيه بى إبروس إفشى إسطاثى تيه.",
                de: "Erhebt euch zum Gebet.",
                ar: "للصلاة قفوا.",
                cop_cop: "",
                ar_de: "Lel salat qefou.",
                cop_de: "E pi pros evshi estathi te.",
            },
            {
                id: 17,
                speaker: "Priester",
                cop_ar: "إيريني باسي.",
                de: "Der Friede sei mit Euch.",
                ar: "السلام لجميعكم.",
                cop_cop: "",
                ar_de: "El salam le gami3ikom.",
                cop_de: "Irini pasi.",
            },
            {
                id: 18,
                speaker: "Volk",
                cop_ar: "كيه طو إبنفماتي سو.",
                de: "Und mit deinem Geiste.",
                ar: "ولروحك أيضاً.",
                cop_cop: "",
                ar_de: "Wa le ro7ika aydan.",
                cop_de: "Ke to pnevmati sou.",
            },
            {
                id: 19,
                speaker: "Priester",
                cop_ar: "مارين شيبئهموت إنتطف إم بيريف إير بيثا نيف أُوه إن نائيت إفنوتي إفيوت إم بين شويس أووه بيننوتي أووه بنسوتير إيسوس بي إخريستوس جي أفئير .  إسكيبازين إيجون آفئير فويثين إيرون أفأريه إيرون آف شوبتين إيروف آف تي آسو إيرون آف تيتوتين آف إينتين شا إى إهري إيطاي أو نوثاي. إنثوف أون مارين تيهوإيروف هوبوس إنتيف آريه إيرون خين باي إيهوؤو إثؤواب فاى نيم ني إيهوؤوتيرو أنتي بين أونخ خين هيريني نيفين إنجي بي بانطوكراطور إبشويس بيننوتي  ",
                de: "Lasst uns Dank sagen dem Wohltaten spendenden und erbarmungsreichen Gott, dem Vater unsers Herrn, Gottes und Erlösers Jesus Christus. Denn er hat uns beschützt, geholfen, bewahrt, angenommen, mit Erbarmen bedacht und bis zu dieser Stunde gelangen lassen. Ihn, den allmächtigen Herrn unseren Gott, bitten wir auch, dass er uns an diesem heiligen Tag und an allen Tagen unseres Lebens in Frieden bewahre.",
                ar: "فلنشكر صانع الخيرات الرحوم الله أبا ربنا وإلهنا ومخلصنا يسوع المسيح. لأنه سترنا وأعاننا وحفظنا وقبلنا إليه. وشفق علينا وعضدنا وأتي بنا إلي هذه الساعة. هو أيضا فلنسأله أن يحفظنا في هذا اليوم المقدس، وكل أيام حياتنا بكل سلام، ضابط الكل الرب الهنا.",
                cop_cop: "",
                ar_de: "Falnashkor sane3 el khayrat el ra7oum Allah Aba Rabbina wa Elahina wa Mokhalisina Yassou3 el Massi7. Le annahu satarana wa a3anana wa 7afazana wa qabilana elayhi. Wa shafaqa 3alayna wa 3adadana wa ata bina ela hazihi el sa3a. Howa aydan fal nas'alhu an ya7fazana fi haza el yom el moqadas, wa kol ayam 7ayatina bekol salam, dabet el kol el Rab Elahina.",
                cop_de: "Maren shep-hmot entotf em-piref er-pethanef owoh en-na-et efnouti efyot em-pen chois owoh pennouti owoh pen-sotir Isos Pkhristos je af-er skepazin ejon af-er voithin eron af-areh eron af-shopten erof af-ti-aso eron af-titotin af-enten sha e-hri e-tai ounou thai. Enthof on maren ti-ho erof hopos entef-areh eron khen pai e-ho-oo ethowab fai nem ni e-ho-oo tiro ente pen onkh khen hirini niven enje pi pantokrator epchois pennouti.",
            },
            {
                id: 20,
                speaker: "Diakon",
                cop_ar: "إبروس إفكصاستيه",
                de: "Betet.",
                ar: "صلوا",
                cop_cop: "",
                ar_de: "Sallou.",
                cop_de: "Pros evxasthe.",
            },
            {
                id: 21,
                speaker: "Volk",
                cop_ar: "كيريه ليسون",
                de: "Herr erbarme Dich.",
                ar: "يارب ارحم",
                cop_cop: "",
                ar_de: "Ya Rab Er7am.",
                cop_de: "Kyrie eleison.",
            },
            {
                id: 22,
                speaker: "Priester",
                cop_ar: "إفنيب إبشويس إفنوتي بي بانطوكراطور إفيوت إمبين شويس أووه بيننوتي أووه بين سوتير إيسوس بي إخرستوس تين شيبئهموت إن توتك كاطا هوب نيفين نيم إثفي هوب نيفين نيم خين هوب نيفين . جي أك إير إسكيبازين إجون أك إيرفويثين إيرون أك أريه إيرون أك شوبتين إيروك أك تي آسو إيرون أك تي توتين أك إين تين شا إى إهري إيطاي أو نو ثاى .",
                de: "Meister, Herr, allmächtiger Gott, Vater unseres Herrn, Gottes und Erlösers Jesus Christus. Wir danken dir für alles, wegen allem und in allem. Denn Du hast uns beschützt, geholfen, bewahrt, uns angenommen, mit Erbarmen bedacht, gestärkt und bis zu dieser Stunde geführt.",
                ar: "أيها السيد الرب الاله ضابط الكل أبو ربنا وإلهنا ومخلصنا يسوع المسيح. نشكرك علي كل حال ومن أجل كل حال وفي كل حال. لأنك سترتنا وأعنتنا وحفظتنا وقبلتنا إليك وأشفقت علينا وعضدتنا، وأتيت بنا إلي هذه الساعة.",
                cop_cop: "",
                ar_de: "Ayouha el sayed el Rab el Elah dabet el kol, Abo Rabbina wa Elahina wa Mokhalisina Yassou3 el Massi7. Nashkoroka 3ala kol 7al wa men agl kol 7al wa fi kol 7al. Le annaka satartana wa a3antana wa 7afaztana wa qabiltana elayk wa shafaqta 3alayna wa 3adadtana, wa atayta bina ela hazihi el sa3a.",
                cop_de: "Ef-nib epchois efnouti pi pantokrator efyot em-pen chois owoh pennouti owoh pen sotir Isos Pkhristos. Ten shep-hmot entotk kata hob niven nem ethvi hob niven nem khen hob niven. Je ak-er skepazin egon ak-er voithin eron ak-areh eron ak-shopten erok ak-ti-aso eron ak-ti-totin ak-en-ten sha e-hri e-tai ounou thai.",
            },
            {
                id: 23,
                speaker: "Diakon",
                cop_ar: "طوبه هينا إنتيه إفنوتي ناي نان: إنتيف شينهيت خارون: إنتيف سوتيم إيه رون: إنتيف إيرفو إيثين إيه رون: إنتيف تشي إن ني تيهو نيم ني طوبه إنتيه ني إثؤواب إنطاف إن طوطو إيه إهري إيه جون إيه بى آغاثون: إنسيو نيفين: إنتيف ايتين ان ائمبشا اشرين اتشي ايفول خين تي كينوني ا انتي نيف ميستيريون إثؤواب اتسمارؤوت ابيكو ايفول انتي نين نوفي",
                de: "Bittet, dass Gott sich unser erbarme: gnädig mit uns sei, uns erhöre und helfe, die Gebete und Bitten seiner Heiligen annehme für unser Wohlergehen zu allen Zeiten, und uns würdig mache, die Teilhabe an seinen heiligen Sakramenten zu erlangen zur Vergebung unserer Sünden.",
                ar: "اطلبوا لكي يرحمنا الله ويتراءف علينا ويسمعنا ويعيننا ويقبل سؤالات وطلبات قديسيه منهم بالصلاح عنا في كل حين ويجعلنا مستحقين أن ننال من شركة أسراره المقدسة المباركة، لمغفرة خطايانا.",
                cop_cop: "",
                ar_de: "Otlobo lekay yar7amana Allah wa yatara'af 3alayna wa yasma3ana wa yo3inana wa yaqbal so'alat wa talabat qadisih minhom bel sala7 3anna fi kol 7in wa yag3alana mosta7iqin an nanal men sharikat asrarihi el moqadasa el mobaraka, le maghfirat khatayana.",
                cop_de: "Tubh hina ente efnouti nai nan: entef shenhit kharon: entef sotem e-ron: entef er-voithin e-ron: entef chi en ni tiho nem ni tovh ente ni ethowab entaf en toto e-hri e-gon e-pi agathon: en-sio niven: entef aiten en empsha etren chi evol khen ti kynonia ente nef mysterion ethowab et-esmaroot ep-iko evol ente nen novi.",
            },
            {
                id: 24,
                speaker: "Volk",
                cop_ar: "كيريه ليسون",
                de: "Herr erbarme Dich.",
                ar: "يارب ارحم",
                cop_cop: "",
                ar_de: "Ya Rab Er7am.",
                cop_de: "Kyrie eleison.",
            },
            {
                id: 25,
                speaker: "Priester",
                cop_ar: "إثفى فاى تين تيهو أووه تين طفه إن تيك ميت آغاثوس بى ما رومى ميس نان إثرين جوك إيفول إم باى كى إيهوؤو إثؤواب فاى نيم نى إيهوؤو تيرو إنتى بين أونخ خين هيريني نيفين نيم تيك هوتى إفثونوس نيفين بى راسموس نيفين إن إرجيا نيفين إنتى إبساطاناس إبسوتشنى إنتى هان رومى إف هوؤو نيم إبطونف إى إبشوى إنتى هان جاجى نى إتهيب نيم نى إثؤأونه إيفول آليتو إيفول هارون نيم إيفول ها بيك لاؤس نيم إيفول هاتاى اترابيزا ثاى تيرف نيم إيفول ها باى ما إثؤواب إنتاك فاى. نى ذى إثنانيف نيم نى إتئر نوفرى ساهنى إموؤو نان جى إثنوك بى اتاكثى إم بى إير شيشى نان إيهومى إيجين نى هوف نيم نى إتشيلى نيم إيجين تى جوم تيرس إنتى بى جاجى.",
                de: "Darum bitten wir und erflehen Deine Güte, Menschenliebender, gewähre uns, diesen heiligen Tag und alle Tage unseres Lebens in völligem Frieden zu vollenden in Ehrfurcht vor dir. Jeden Neid, jede Versuchung, alle Werke des Satans, die Nachstellungen böser Menschen und das Hervorkommen von Feinden, Verborgenen oder offenkundig halte fern von uns, und von deinem ganzen Volk und von diesem Tische und von diesem deinem heiligen Ort. Die guten und die nützlichen Dinge aber lass uns zuteil werden, denn du hast uns Macht gegeben, auf Schlangen und Skorpione und jegliche Macht des Feindes zu treten.",
                ar: "من اجل هذا نسأل ونطلب من صلاحك يا محب البشر امنحنا أن نكمل هذا اليوم المقدس وكل أيام حياتنا بكل سلام مع خوفك كل حسد وكل تجربة وكل فعل الشيطان ومؤامرة الناس الأشرار وقيام الأعداء الخفيين والظاهـرين إنزعها عنا وعن سائر شعبك وعن هذه المائدة وعن موضعك المقدس هذا. أما الصالحات والنافعات فإرزقنا إياها لأنك أنت الذي أعطيتنا السلطان أن ندوس الحيات والعقارب وعلي كل قوة العدو",
                cop_cop: "",
                ar_de: "Min agl haza nas'al wa natlob men sala7eka ya mo7eb el bashar emna7na an nokamel haza el yom el moqadas wa kol ayam 7ayatina bekol salam ma3a khawfeka kol 7asad wa kol tagroba wa kol fe3l el shaytan wa mo'amarat el nas el ashrar wa qiyam el a3da' el khafyin wal zaherin inza3ha 3anna wa 3an sa'er sha3beka wa 3an hazihi el ma'eda wa 3an mawde3eka el moqadas haza. Amma el sale7at wal nafe3at farzoqna iyaha le annaka anta allazi a3taytana el soltan an nadous el 7ayat wal 3aqareb wa 3ala kol qowat el 3adow.",
                cop_de: "Ethve fai ten tiho owoh ten tovh en tek met aghathos pi mai romi mis nan ethren jok evol em pai ke eho-oo ethowab fai nem ni eho-oo tiro ente pen onkh khen hirini niven nem tek hoti efthonos niven pirasmos niven energiah niven ente epsatanas ep-sotchni ente han romi ef ho-oo nem ep-tonf e ep-shoi ente han jaji ni et-hip nem ni eth-ouonh evol ali-tou evol haron nem evol ha pek laos nem evol ha tai trapeza thai tirf nem evol ha pai ma ethowab entak fai. Ni de eth-nanev nem ni et-er nofri sahni emo-oo nan je enthok pe atak-ti em pi er shishi nan e-homi ejen ni hof nem ni jli nem ejen ti jom tirs ente pi jaji.",
            },
            {
                id: 26,
                speaker: "Volk",
                cop_ar: "سوتيس آمين كي طو بنيڤماتي سو",
                de: "Erlöst Amen und mit deinem Geiste",
                ar: "خلصت حقا ولروحك.",
                cop_cop: "",
                ar_de: "Khollist 7aqqan wa le ro7ika.",
                cop_de: "Sotis amin ke to pnevmati sou.",
            },
            {
                id: 27,
                sectionTitle: {
                    de: "Absolution der Dienenden",
                    ar: "تحليل الخدام"
                },
                speaker: "p",
                ar: "عبيدك يا رب خدام هذا اليوم القمامصة والقسوس والشمامسة والاكليروس وكل الشعب وضعفي يكونون محاللين من فم الثالوث القدوس الآب والابن والروح القدس ومن فم الكنيسة الواحدة الوحيدة المقدسة الجامعة الرسولية ومن أفواه الاثني عشر رسولا ومن فم ناظر الاله الإنجيلى مرقس الرسول الطاهر والشهيد والبطريرك القديس ساويرس ومعلمنا ديوسقورس والقديس أثناسيوس الرسولي والقديس بطرس خاتم الشهداء رئيس الكهنة والقديس يوحنا ذهبي الفم والقديس كيرلس والقديس باسيليوس والقديس اغريغوريوس ومن أفواه الثلاثمائة والثمانية عشر المجتمعين بنيقية والمئة والخمسين بالقسطنطينية والمائتين بأفسس ومن فم أبينا المكرم رئيس الكهنة البابا أنبا تواضرس الثانى وشركاءه  في الخدمة الرسولية ابونا المطران المكرم الانبا دميان .و ابونا الاسقف المكرم الانبا ديسقورس ومن فم حقارتي. لانه مبارك ومملوء مجدا اسمك القدوس أيها الآب والابن والروح القدس الآن وكل أوان وإلي دهر الدهور كلها آمين. ",
                de: "Deine Diener an diesem Tag, Die Erzpriester, Die Priester, Die Diakone, Kleriker, das ganze Volk und ich Schwacher, seien alle losgesprochen durch den Mund der Heiligen Dreifaltigkeit, des Vaters, des Sohnes und des Heiligen Geistes, durch den Mund der einen, einzigen, heiligen, universalen und apostolischen Kirche, durch den Mund der zwölf Jünger, durch den Mund des Gottessehers, des Evangelisten, Apostels und Märtyrers Markus, des Patriarchen Hl. Severus, unseres Lehrers Dioskorus, des apostelgleichen Athanasius,des Hl. Märtyrers und Papstes Petrus, des Hl. Johannes Chrisosthomus, des Hl. Kyrillus, des Hl. Basilius, des Hl. Gregorius, und durch den Mund der dreihundertachtzehn versammelten Väter in Nicea, der einhundertfünfzig in Konstantinopel und der zweihundert zu Ephesus versammelten Väter; und durch den Mund unseres ehrwürdigen Vaters, des Papstes Anba Tawadeos II  und durch seine Teilhaber am apostolischen Dienst, unseren ehrwürdigen Vater, Erzbischof Anba Damian, und unseren ehrwürdigen Vater, Bischof Anba Dioskorus.  durch den Mund meiner Niedrigkeit, denn gepriesen und voll der Ehre sei Dein Heiliger Name, o Vater, Sohn und Heiliger Geist. Jetzt, alle Zeit und in Ewigkeit. Amen.",
                ar_de: "3abeedoka ya Rab khoddam haza el yom el qamamisa wal qosous wal shamamesa wal ekliros wa kol el sha3b wa da3fi yakounoun mo7alalin men fam el thalouth el qoddos el Ab wal Ebn wal Ro7 el Qodos wa men fam el kanisa el wa7ida el wa7ida el moqadasa el game3a el rasoliya wa men afwah el ethnay 3ashar rasoula wa men fam nazer el elah el ingili Morqos el rasoul el taher wal shahid wal batriark el qadis Sawiros wa mo3alimina Dioscoros wal qadis Athanasios el rasouli wal qadis Botros khatem el shohada' ra'is el kahana wal qadis Youhanna zahabi el fam wal qadis Kirollos wal qadis Basilios wal qadis Aghrioghorios wa men afwah el thalathema'a wal thamaniat 3ashar el mogtame3in be Niqia wal me'a wal khamsin bel Qostantinya wal ma'etayn be Afasos wa men fam abina el mokaram ra'is el kahana el Baba Anba Tawadros el thani wa shoraka'ihi fil khidma el rasoliya abouna el motran el mokaram el Anba Damian wa abouna el osqof el mokaram el Anba Dioscoros wa men fam 7aqarati. Le annahu mobarak wa mamlou' magdan ismoka el qoddos ayouha el Ab wal Ebn wal Ro7 el Qodos el an wa kol awan wa ela dahr el dohour kollaha. Amin.",
            },
            {
                id: 28,
                speaker: "Volk",
                cop_ar: "سوتيس آمين كي طو بنيڤماتي سو",
                de: "Erlöst Amen und mit deinem Geiste",
                ar: "خلصت حقا ولروحك.",
                cop_cop: "",
                ar_de: "Khollist 7aqqan wa le ro7ika.",
                cop_de: "Sotis amin ke to pnevmati sou.",
            },
            {
                id: 27,
                speaker: "Volk",
                cop_ar: "طاى شورى إن نوب إنكاثاروس: إت فاى خابى آروماطا: إت خين نين جيج إن آ آرون بى أوويب: إف طاليه أو إسطوى نوفى إيه إبشوى إيه جين بى ما إن إيرشو أوشى.",
                de: "Dies ist das Weihrauchgefäß aus reinem Gold, das den lieblichen Duft enthält, in der Hand des Priesters Aarons, der den Weihrauch über dem Altar emporhebt.",
                ar: "هذه المجمرة الذهب النقي الحاملة العنبر التي في يدي هرون الكاهن يرفع بخوراً فوق المذبح.",
                cop_cop: "",
                ar_de: "Hazihi el magmara el zahab el naqi el 7amila el 3anbar allati fi yaday Haroun el kahen yarfa3 bokhouran fawq el mazba7.",
                cop_de: "Tai shori en noub en-katharos: et fai kha pi aromata: et khen nen jij en A-aron pi ouib: ef tale o es-toi novi e ep-shoi e jen pi ma en er-sho oushi.",
            },
            {
                id: 28,
                speaker: "Volk",
                cop_ar: "هيتين ني إبريسفيا إنتيه تي ثيه أوطوكوس إثؤواب ماريا: إبتشويس آري إهموت نان إمبي كو إيفول إنتيه نين نوفي.",
                de: "Durch die Fürsprache der Mutter Gottes, der heiligen Maria, gewähre uns, o Herr, die Vergebung unserer Sünden",
                ar: "بشفاعات والدة الاله القديسة مريم. يارب انعم لنا بمغفرة خطايانا.",
                cop_cop: "",
                ar_de: "Bi shafa3at walidat el elah el qadisa Mariam. Ya Rab an3im lana be maghfirat khatayana.",
                cop_de: "Hiten ni presvia ente ti theotokos ethowab Maria: Epchois ari-hmot nan em-pi ko evol ente nen novi.",
            },

            {
                id: 29,
                speaker: "Volk",
                cop_ar: "هيتين ني إبريسفيا إنتيه بي شاشف إن أرشي أنجيلوس نيم ني طغما ان إيه بورانيون. إبتشويس...",
                de: "Durch die Fürsprache der sieben Erzengel und der Himmlischen Ränge, gewähre uns, o Herr, die Vergebung unserer Sünden.",
                ar: "بشفاعات السبعة رؤساء الملائكة والطغمات السمائية. يارب...",
                cop_cop: "",
                ar_de: "Bi shafa3at el sab3a ro'asa' el mala'ika wal taghmat el sama'iya. Ya Rab...",
                cop_de: "Hiten ni presvia ente pi shashf en arshi angelos nem ni taghma en e-poranion. Epchois...",
            },
            {
                id: 30,
                speaker: "Volk",
                cop_ar: "هيتين ني إفشى إنتيه ناشويس إنيوتى إن أبو سطولوس نيم إبسييه بي إنتيه ني ما ثيتيس: إبتشويس...",
                de: "Durch die Fürsprache unserer Herren und Väter, der Apostel und Jünger, gewähre uns, o Herr, die Vergebung unserer Sünden.",
                ar: "بصلوات سادتى الاباء الرسل والتلاميذ. يارب...",
                cop_cop: "",
                ar_de: "Bi salawat sadati el aba' el rosol wal talamiz. Ya Rab...",
                cop_de: "Hiten ni evshi ente na-chois en-yoti en apostolos nem ep-sepi ente ni mathitis: Epchois...",
            },
            {
                id: 31,
                speaker: "Volk",
                cop_ar: "هيتين ني إفشى إنتيه بي ثيه أوريموس إن إف آنجيليستيس ماركوس بي أبو سطولوس... إبتشويس...",
                de: "Durch die Fürsprache des Gottsehers, des Evangelisten Markus, des Apostels, gewähre uns, o Herr, die Vergebung unserer Sünden.",
                ar: "بصلوات ناظر الاله الانجيلي مرقس الرسول. يارب...",
                cop_cop: "",
                ar_de: "Bi salawat nazer el elah el ingili Morqos el rasoul. Ya Rab...",
                cop_de: "Hiten ni evshi ente pi theorimos en evangelistis Markos pi apostolos... Epchois...",
            },
            {
                id: 32,
                speaker: "Volk",
                cop_ar: "هيتين نى إفشى إنتى بى اثلوفوروس ام مارتيروس باشويس ابؤرو جوارجيوس فيلوباتير مارقوريوس افا مينا انتى نى فايات. إبتشويس......",
                de: "Durch die Fürsprache des heiligen Kämpfer und Märtyrers George, Philopatirs Mercurius, abba Mina von Waiat gewähre uns, o Herr, die Vergebung unserer Sünden.",
                ar: "بصلوات المجاهد الشهيد سيدي الملك جيورجيوس . فيلوباتير مرقوريوس أنبا مينا . . . . يا رب",
                cop_cop: "",
                ar_de: "Bi salawat el mogahed el shahid sayedi el malek Georgios. Philopater Morqorios Anba Mina.... Ya Rab",
                cop_de: "Hiten ni evshi ente pi athloforos em martyros pa-chois ep-ouro Georgios Philopatir Mercurios ava Mina ente ni Fayat. Epchois...",
            },
            {
                id: 33,
                speaker: "Volk",
                cop_ar: "هيتين ني إفشي انتي ني شيليت انتي بخرستوس تي أجيا إمي باربارا نيم يولياني نيم دمياني نيم ماريني: ابتشويس ....",
                de: "Durch die Fürsprache der Bräute Christi und des heiligen Barbara Ulianh und Demiana und Marina. o Herr, die Vergebung unserer Sünden",
                ar: "بصلوات عرائس المسيح القديسات بربارة و يوليانا ودميانة ومارينا. يارب...",
                cop_cop: "",
                ar_de: "Bi salawat 3ara'es el Massi7 el qadisat Barbara wa Juliana wa Demiana wa Marina. Ya Rab...",
                cop_de: "Hiten ni evshi ente ni shelet ente Pkhristos ti agia emmi Barbara nem Yuliani nem Demiani nem Marini: Epchois...",
            },
            {
                id: 34,
                speaker: "Volk",
                cop_ar: "هيتين ني إفشى إنتى ناتشويس إنيوتى إمماي نوشيري آبا أنطونيوس نيم آبا بافلي نيم باخوميوس نيم بي شومت إثؤواب مكاريوس آبا شينوتي بي آرشي ماندريتيس: إبتشويس...",
                de: "Durch die Fürbitten meiner Herren und Väter, die ihre Kinder lieben, Anba Antonius und Anba Paul und der Abba Pachom und heiligen 3 Anba Makarios und Anba Shenouda der Archimandriten, o Herr, die Vergebung unserer Sünden",
                ar: "بصلوات سادتي الآباء محبي أولادهما أنبا أنطونيوس وأنبا بولا وباخوميوس والثلاث مقارات القديسين وأنبا شنودة رئيس المتوحدين، يارب ...",
                cop_cop: "",
                ar_de: "Bi salawat sadati el aba' mo7ebi awladehima Anba Antonios wa Anba Bola wa Bakhomios wal thalath maqarat el qadisin wa Anba Shenouda ra'is el motawa7edin, Ya Rab...",
                cop_de: "Hiten ni evshi ente na-chois en-yoti emmai no-shiri Ava Antonios nem Ava Pavli nem Pachomios nem pi shomt ethowab Makarios Ava Shenouti pi archimandritis: Epchois...",
            },
            {
                id: 35,
                speaker: "Volk",
                cop_ar: "هيتين نى إفشى إنتى نينيوتى إثؤواب إم بطريارشيس آفا أثناسيوس بى أبوستوليكوس نيم آفا كيرلوس بستيلوس إنتى بى ناهتى نيم ديسقوروس إبخيبيس إنتى تى أورثوذكسيا إبتشويس.....",
                de: "Durch die Fürbitten unserer Väter, der heiligen Patriarchen: Abba Athanasius, der Apostelgleiche, Abba Kyrillus, die Glaubenssäule, Dioskorus, die Leuchte der Orthodoxie gewähre uns, o Herr, die Vergebung unserer Sünden.",
                ar: "بصلوات الإباء البطاركة القديسين . انبا اثناسيوس الرسولي ، والانبا كيرلس عمود الإيمان وديسقوروس مصباح الأرثوذكسية يارب...",
                cop_cop: "",
                ar_de: "Bi salawat el aba2 el batarika el qadisin. Anba Athanasios el rasouli, wal Anba Kirollos 3amoud el iman wa Dioscoros mosba7 el orthodoxia Ya Rab...",
                cop_de: "Hiten ni evshi ente ninyoti ethowab em patriarchis Ava Athanasios pi apostolikos nem Ava Kyrollos pi stilos ente pi nahti nem Dioscorus ep-khibis ente ti orthodoxia Epchois...",
            },
            {
                id: 36,
                speaker: "Volk",
                cop_ar: "هيتين ني إفشى إنتيه ني إثؤواب إنتيه باي إيه هوؤو بي أوواي بي أوواي كاطا بيفران: إبتشويس...",
                de: "Durch die Fürsprache des Heiligen des heutigen Tages, durch jeden mit seinen Namen, gewähre uns, o Herr, die Vergebung unserer Sünden.",
                ar: "بصلوات قديسي هذا اليوم كل واحد و واحد بأسمه. يارب...",
                cop_cop: "",
                ar_de: "Bi salawat qadisi haza el yom kol wa7ed wa wa7ed be esmeh. Ya Rab...",
                cop_de: "Hiten ni evshi ente ni ethowab ente pai e-ho-oo pi ouai pi ouai kata pefran: Epchois...",
            },
            {
                id: 37,
                speaker: "Volk",
                cop_ar: "هيتين نو إفشى آريه إبؤنخ إم بينيوت إت طايوت إن أرشى إيه ريقس بابا آڤا (تواضروس): إبتشويس....",
                de: "Durch ihre Fürsprachen behüte das Leben unseres ehrwürdigen Vaters, Priesteroberhaupt, Papst Anba Tawadros II , gewähre uns, o Herr, die Vergebung unserer Sünden.",
                ar: "بصلواتهم احفظ حياة ابينا المكرم رئيس الكهنة البابا الانبا تواضروس يارب انعم لنا بمغفرة خطايانا.",
                cop_cop: "",
                ar_de: "Bi salawatehim ehfaz 7ayat abina el mokaram ra'is el kahana el Baba el Anba Tawadros ya Rab an3im lana be maghfirat khatayana.",
                cop_de: "Hiten no evshi areh ep-onkh em-penyot et-tayout en-archi erevs papa ava Tawadros: Epchois...",
            },
            {
                id: 38,
                speaker: "Volk",
                cop_ar: "هيتين نو إفشى آريه إبؤنخ إم بنيوت إتطايوت إن ذيكئوس أفا ديمان بي ميتروبوليتيس نيم آفا ديسقورس بي إبسكوبوس آري إهموت نان إمبى كو إيفول إنتى نين نوفي",
                de: "Durch ihre Fürbitten behüte das Leben unserer ehrwürdigen Väter, der Erzbischof Anba Damian und Bischof Anba Dioskoros, gewähre uns, o Herr, die Vergebung unserer Sünden.",
                ar: "بصلواتهم، احفظ يا رب حياة آبائنا المكرَّمين، المطران الأنبا دميان والاسقف الأنبا ديسقورس، وأنعمْ علينا بمغفرة خطايانا.",
                cop_cop: "",
                ar_de: "Bi salawatehim, e7faz ya Rab 7ayat aba'ina el mokaramin, el motran el Anba Damian wal osqof el Anba Dioscoros, wa an3em 3alayna be maghfirat khatayana.",
                cop_de: "Hiten no evshi areh ep-onkh em-penyot et-tayout en-dikeos Ava Damian pi metropolitis nem Ava Dioscoros pi episkopos ari-hmot nan em-pi ko evol ente nen novi.",
            },
            {
                id: 39,
                speaker: "Volk",
                cop_ar: "تين أوأوشت إممو ك أو بخرستوس: نيم بيك يوت إن آغاثوس: نيم بي إبنفما إثؤواب: جيه أكطونك أك سوتي إممون ناي نان.",
                de: "Wir beten dich an, o Christus, zusammen mit deinem guten Vater, und dem Heiligen Geist, denn Du bist auferstanden und hast uns erlöst.",
                ar: "نسجد لك أيها المسيح مع أبيك الصالح والروح القدس، لأنك قمت وخلصتنا.",
                cop_cop: "",
                ar_de: "Nasgod laka ayoha el Massi7 ma3a abika el sale7 wal ro7 el qodos, le annaka qomta wa khallastana.",
                cop_de: "Ten ou-osht emmok o Pkhristos: nem pek yot en aghathos: nem pi pnevma ethowab: je ak-tonk ak soti emmon nai nan.",
            },
            {
                id: 40,
                sectionTitle: {
                    de: "Der Paulusbrief",
                    ar: "البولس"
                },

                speaker: "D",
                de: "Die Gnade Gottes des Vaters sei mit Euch,meine Väter und Brüder Amen. ",
                ar: "نعمة الله الآب فلتحل على أرواحنا يا آبائي وإخوتي. آمين ",
                cop_cop: "",

            },
            {
                id: 41,
                sectionTitle: {
                    de: "Der Katholische Brief",
                    ar: "الكاثوليكون"
                },
                speaker: "D",
                de: "Liebt nicht die Welt und was in der Welt ist .Die Welt Und iher Begierden vergehen . Wer aber den Willen Gottes tut, bleibt in Ewigkeit. Amen ",
                ar: "(لا تحبوا العالم ولا الأشياء التي في العالم؛ لأن العالم يمضي وشهوته معه ، و أما من يعمل مشيئة الله فإنه يثبت إلى الأبد آمين )",
            },
            {
                id: 40,
                speaker: "Volk",
                cop_ar: "شيريه ني ماريا: تي إتشرومبي إثنيه سوس: ثي إيه طاس ميسي نان: إم إفنوتي بي لوغوس. إك إسمارؤوت آليثوس نيم بيك يوت إن آغاثوس: نيم بي إبنفما إثؤواب: جيه (أكئي / أكطونك) أكسوتي إممون ناي نان.",
                de: "Gegrüßt seist du Maria, du schöne Taube, die uns Gott das Wort gebar. Wahrhaftig gepriesen seist Du mit Deinem guten Vater und dem heiligen Geist, denn Du bist (gekommen/auferstanden) und hast uns erlöst.",
                ar: "السَّلَامُ لَكِ يَا مريم، الحَمامة الحَسَنة، التي ولَدت لنا، الله الكَلمة. مبارك أنت مع أبيك الصالح، والروح القدس، لأنك (أتيت/ قُمْتَ) وخلصتنا. ارحمنا.",
                cop_cop: "",
                ar_de: "El salam laki ya Mariam, el 7amama el 7asana, allati waladat lana, Allah el Kalima. Mobarak anta ma3a abika el sale7, wal ro7 el qodos, le annaka (atayta/ qomta) wa khallastana. Er7amna.",
                cop_de: "Shere ne Maria: ti-etshrompi ethnesos: thi-etas-misi nan: em-efnouti pi-logos. Ek-esmaroot alithos nem pek yot en aghathos: nem pi pnevma ethowab: je (ak-i / ak-tonk) ak soti emmon nai nan.",
            },
            {
                id: 41,
                sectionTitle: {
                    de: "Der Apostelgeschichte",
                    ar: "الابركسيس"
                },
                de: "Das Wort Gottes möge wachsen, sich ausbreiten, stark werden und fest bleiben in der heiligen Kirche Gottes. Amen. ",
                ar: "لم تزل كلمة الرب تنمو وتكثر وتعتز وتثبت ، في بيعة الله المقدسة. آمين",
            },




            {
                id: 6,
                speaker: "P",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",

            },
        ]
    },
    // --- BASILIUS LITURGIE ---
    basily: {
        title: {
            de: "Die Göttliche Liturgie des Hl. Basilius",
            ar: "القداس الإلهي للقديس باسيليوس"
        },
        content: [
            {
                id: 1,
                speaker: "Volk",
                cop_ar: "Eporo...",
                de: "Wir glauben an den einen Gott: Gott den Vater , den Allmächtigen, Schöpfer des Himmels und der Erde, alles Sichtbaren und Unsichtbaren.Wir glauben an den einen Herrn Jesus Christus , Gottes einzigen Sohn, geboren aus dem Vater vor aller Zeit Licht vom Lichte , wahrer Gott vom wahren Gott, gezeugt, nicht geschaffen, eines Wesens mit dem Vater; durch ihn ist alles geworden. , nicht geschaffen, eines Wesens mit dem Vater; durch ihn ist alles geworden.  Für uns Menschen und um unseres Heils willen ist er vom Himmel herabgestiegen. Er hat Fleisch angenommen durch den Heiligen Geist, von der Jungfrau Maria und ist Mensch geworden. Er wurde gekreuzigt unter Pontius Pilatus an unserer Statt,hat gelitten und ist begraben worden.Am dritten Tag auferstanden von den Toten gemäß der Schrift,aufgefahren in den Himmel, sitzt er zur Rechten seines Vaters Und so wird er wiederkommen in seiner Herrlichkeit, zu richten die Lebenden und die Toten, und seiner Herrschaft wird kein Ende sein.Ja, wir glauben an den Heiligen Geist, der Herr ist und lebendig macht, der aus dem Vater hervorgeht , der mit dem Vater und dem Sohn angebetet und verherrlicht wird. Er hat gesprochen durch die Propheten Wir glauben an die eine heilige, universale und apostolische Kirche. Wir bekennen die eine Taufe zur Vergebung der Sünden. Wir erwarten die Auferstehung der Toten und das Leben der kommenden Welt. Amen.",
                ar: "بالحقيقة نؤمن بإله واحد الله الآب ضابط الكل خالق السماء والأرض ما يُرى وما لا يُرى نؤمن برب واحد يسوع المسيح ابن الله الوحيد المولود من الآب قبل كل الدهور نور من نور إله حق من إله حق مولود غير مخلوق ، مساوٍ للآب فى الجوهـر الذى به كان كل شيء هذا الذى من أجلنا نحن البشر ومن أجل خلاصنا نزل من السماء وتجسد من الروح القدس ومن مريم العذراء وتأنس وصلب عنا على عهد بيلاطس البنطي تألم وقبر وقام من بين الاموات فى اليوم الثالث كما فى الكتب وصعد الى السموات وجلس عن يمين أبيه وأيضاً يأتى فى مجده ليدين الاحياء والاموات الذى ليس لملكه انقضاء نعم نؤمن بالروح القدس الرب المحيي المنبثق من الآب. نسجد له ونمجده مع الآب والابن الناطق فى الأنبياء وبكنيسة واحدة مقدسة جامعة رسولية ونعترف بمعمودية واحدة لمغفرة الخطايا وننتظر قيامة الأموات وحياة الدهر الآتى .آمين",
                cop_cop: "Ⲡϭⲟⲓⲥ...",
                ar_de: "Bel 7aqiqa no2men be elah wa7ed, Allah el Ab dabet el kol, 5aleq el sama wal ard, ma yora wa ma la yora. No2men be rab wa7ed Yassou3 el Massi7, Ebn Allah el wa7id, el mawloud men el Ab qabl kol el dohour. Nour men Nour, Elah 7aq men Elah 7aq, mawloud gheir ma5louq, mosawen lel Ab fel gawhar, allazy bihi kan kol shay2. Haza allazy men aglina na7n el bashar, wa men agl 5alasna, nazal men el sama, wa tagassad men el Ro7 el Qodos wa men Mariam el 3azra2 wa ta2anas. Wa soleb 3anna 3ala 3ahd Bilatos el Bonti, ta2alam wa qober wa qam men bein el amwat fel yom el thaleth kama fel kotob. Wa sa3ad ela el samawat, wa galas 3an yamin abih. Wa aydan ya2ti fi magdehi le yadin el a7ya2 wal amwat, allazy laysa le molkehi enqida2. Na3am no2men bel Ro7 el Qodos, el Rab el mo7yi, el monbathiq men el Ab. Nasgod lahu wa nomagedohu ma3 el Ab wal Ebn, el nateq fel anbya2. Wa be kanisa wa7da moqadasa game3a rasoulya. Wa na3taref be ma3moudia wa7da le maghferet el 5ataya. Wa nantazer qiyamat el amwat, wa 7ayat el dahr el aaty. Amin.",
                cop_de: "Ep-chois...",
            },
            {
                id: 2,
                sectionTitle: {
                    de: "Die Auswahl des Lammbrotes",
                    ar: "تقديم الحمل"
                },
                speaker: "Volk",
                cop_ar: "Ke to pnevmati so...",
                de: "Und mit deinem Geiste.",
                ar: "كيريه ليسون كيريه ليسون يارب ارحم\nكيريه ليسون كيريه ليسون ارحمنا يا الله\nكيريه ليسون كيريه ليسون اسمعنا و ارحمنا",
                cop_cop: "Kurie `ele`ycon.",
                ar_de: "Wa li-ruhika aydan",
                cop_de: "Ke to pnewmati su...",
            },
        ],
    },

    // --- GREGORIOS LITURGIE (8ere8orios) ---
    gregorios: {
        title: {
            de: "Die Liturgie des Hl. Gregorios",
            ar: "القداس الغريغوري",
        },
        content: [
            {
                id: 1,
                speaker: "Priester",
                cop_de: "",
                de: "Betet",
                ar: "صلوا",
                cop_cop: "; Sl/l",
                ar_de: "",
                cop_ar: "إشلـــــــيل",
            },
            {
                id: 2,
                speaker: "Diakon",
                cop_de: "",
                de: "Erhebt euch zum Gebet",
                ar: "للصلاة قفوا",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إيه بى إبروس إفشى إسطاثى تيه",
            },
            {
                id: 3,
                sectionTitle: {
                    de: "Das Versöhnungsgebet",
                    ar: "صلاة الصلح"
                },
                speaker: "Priester",
                cop_de: "",
                de: "Der Friede seit mit allen",
                ar: "السلام لجميعكم",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إيرينى باسى",
            },
            {
                id: 4,
                speaker: "Volk",
                cop_de: "",
                de: "Und mit deinem Geiste",
                ar: "ولروحك أيضا",
                cop_cop: "",
                ar_de: "",
                cop_ar: "كيه طو إبنفماتى سو",
            },
            {
                id: 5,
                speaker: "priester",
                cop_de: "",
                de: "Der Du bist,der Du warst und der Du sein Wirst bis in Ewigkeit ,der Wesensgleiche,Mitthorneden und Gefährte des Schöpfers und Vaters Der Du aus alleiniger Güte den Menschen aus dem Nichts geschaffen hast und ihn ins Paradies der Freude gesetzt hast. Als er aber durch die Täuschung des Feindes und den Ungehorsam gegen Dein heiliges Gebot fiel  und Du ihn in die frühere Würde bringen wolltest hast Du weder einem Engel ,noch einem Erzengel,noch einem propheten unsere Erlösung  anvertraut. Sondern du hast selber ohne Veränderung Fleisch angenommen und bist Mensch geworden, und bist uns in allem gleich geworden außer allein in der Sünde Du wurdest uns ein Mittler bei dem Vater, du hast die trennende Wand niedergerissen und die alte Feindschaft aufgehoben.Du hast  die Irdischen mit den Himmlischen versöhnt und die zwei eins gemacht, nachdem du die Heilsordnung im Fleisch vollendet hast. Als du empor Himmel leiblich aufgefahren bist ,hast du alles mit deiner Gottheit erfüllt. Du hast zu deinen heiligen Jüngern und Aposteln gesagt Meinen Frieden gebe ich euch ,meinen Frieden hinterlasse ich euch. Gewähre ihn uns , unser Herr. Reinige uns von aller Befleckung, allem Betrug, aller Heuchelei, jeder listigen Tat und vom Denken an das Böse, das den Tod nach sich zieht.",
                ar: "أيها الكائن الذى كان الدائم إلي الأبد، الذاتي والمساوي والجليس والخالق الشريك مع الآأيها الكائن الذى كان الدائم إلي الأبد، الذاتي والمساوي والجليس والخالق الشريك مع الآب، الذى من أجل الصلاح وحده مما لم يكن كونت الانسان وجعلته في فردوس النعيم وعندما سقط بغواية العدو ومخالفة وصيتك المقدسة وأردت أن تجدده وترده إلي رتبته الأولى لا ملاك ولا رئيس ملائكة ولا رئيس آباء ولا نبياً ائتمنته على خلاصنا . بل أنت بغير استحالة تجسدت وتأنست وشابهتنا في كل شيء ما خلا الخطيئة وحدها وصرت لنا وسيطاً لدى الآب، والحاجز المتوسط نقضته والعداوة القديمة هدمتها وأصلحت الأرضيين مع السمائيين، وجعلت الأثنين واحداً، وأكملت التدبير بالجسد وعند صعودك إلي السموات جسدياً إذ ملأت الكل بلاهوتك قلت لتلاميذك ورسلك القديسين سلامى أعطيكم سلامى أنا أترك لكم، هذا أيضاً الآن أنعم به علينا يا سيدنا طهرنا من كل دنس، ومن كل غش، ومن كل رياء، ومن كل شر، ومن كل مكيدة، ومن تذكار الشر الملبس الموت.",
                cop_cop: "",
                ar_de: "",
                cop_ar: "",
            },
            {
                id: 6,
                speaker: "Diakon",
                cop_de: "",
                de: "Betet für den vollkommenen Frieden, für die Liebe und die apostolischen reinen Küsse.",
                ar: "صلوا من أجل السلام الكامل والمحبة والقبلة الطاهرة الرسولية",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إبروس افكصاستيه إي برتيس تيه لياس إيرينيس كيه آغابيس كيه طون آجيون إسباسمون طون أبوسطولون",
            },
            {
                id: 7,
                speaker: "Volk",
                cop_de: "",
                de: "Herr erbarme dich",
                ar: "يارب ارحم ",
                cop_cop: "",
                ar_de: "",
                cop_ar: "كيريه ليسون",
            },
            {
                id: 8,
                speaker: "Priester",
                cop_de: "",
                de: "Mach uns  alle würdig, o Herr , einander mit  einem reinen Kuss zu grüßen Damit wir ,ohne uns Verurteilung einzuhandeln,  deine unsterblichen und himmlischen Gaben erlangen durch deine Gnade und das Wohlgefallen deines guten Vaters und das Wirken deines heiligen Geistes, denn du bist Versorgen und Spender aller Güter",
                ar: "واجعلنا مستحقين كلنا يا سيدنا أن نقبل بعضنا بعضاً بقبلة طاهرة، لنتناول بغير انطراح في الحكم من موهبتك غير المائتة السمائية، بنعمتك ومسرة أبيك الصالح وفعل روحك القدوس، لأنك أنت الرازق ومُعطى جميع الخيرات.",
                cop_cop: "",
                ar_de: "",
                cop_ar: "",
            },
            {
                id: 9,
                speaker: "Diakon",
                cop_de: "",
                de: "Küsst einander mit einem heiligen Kuss. (Herr erbarme Dich)* 3 Ja o Herr Jesus Christus, Sohn Gottes, erhöre uns und erbarme Dich unser. Tretet heran nach der Vorschrift, steht in Ehrfurcht und schaut nach Osten. Wir hören.",
                ar: ".قبلوا بعضكم بعضاً بقبلةٍ مقدسة. (يارب ارحم)* ۳ نعم يارب الذي هو يسوع المسيح ابن الله الحي، اسمعنا وارحمنا. تقدموا تقدموا تقدموا على الرسم، قفوا برعدة، والي الشرق أنظروا. ننصت",
                cop_cop: "",
                ar_de: "",
                cop_ar: "أسـپـاذسـتي ألليلوس إن فـيلـيـمـاتی  آجـيو. (كيريي إليسوس) * ۳ نای كيريي إيتي فای پي إيسـوس پي إخـرسـتـوس إبشير إم إفنوتى سوتيم إيرون أووه ناي نان. إبروسفرين كاطا إطربو إستـاثيتي كـاطـا إطرومـوايس أناطولاس إفليـبساتـي إبروس خـومين. ",
            },
            {
                id: 10,
                speaker: "Volk",
                cop_de: "",
                de: "Durch die Fürsprachen der Mutter Gottes, der Heiligen Maria, vergib uns, o Herr, unsere Sünden durch Deine Gnade.Wir beten dich an, o Christus, zusammen mit deinem guten Vater, und dem Heiligen Geist,denn du bist (auferstanden/gekommen) und hast uns erlöst. Erbarmen des Friedens, Opfer des Lobes ",
                ar: "بشفاعات والدة الإله القديسة مريم يارب انعم لنا بمغفرة خطايانا نسجد لك أيها المسيح مع أبيك الصالح والروح القدس لأنك (أتيت/قُمت) وخلصتنا رحمة السلام ذبيحة التسبيح",
                cop_cop: "",
                ar_de: "",
                cop_ar: "هيتين نيه إبريسفيا إنتيه تى ثيه أوطوكوس إثؤواب ماريا: إبتشويس آرى إهموت نان إمبى كو إيفول إنتيه نين نوفي. تين أوأوشت إمموك أو بخرستوس: نيم بيك يوت إن آغاثوس: جيه (آك إي/أكطونك) أكسوتي إممون: إيه ليه أوس إيرينيس ثي سيا إيه نيه ثيه أوس",
            },
            {
                id: 11,
                speaker: "",
                cop_de: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_ar: "",
            },
        ],
    },

    // --- CYRILLUS LITURGIE (Kerollosy) ---
    kerollosy: {
        title: {
            de: "Die Liturgie des Hl. Cyrillus",
            ar: "القداس الكيرلسي",
        },
        content: [
            {
                id: 1,
                speaker: "Priester",
                cop_de: "",
                de: "Betet",
                ar: "صلوا",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إشلـــــــيل",
            },
            {
                id: 2,
                speaker: "Diakon",
                cop_de: "",
                de: "Erhebt euch zum Gebet",
                ar: "للصلاة قفوا",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إيه بى إبروس إفشى إسطاثى تيه",
            },
            {
                id: 3,
                speaker: "Priester",
                cop_de: "",
                de: "Der Friede seit mit allen",
                ar: "السلام لجميعكم",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إيرينى باسى",
            },
            {
                id: 4,
                speaker: "Volk",
                cop_de: "",
                de: "Und mit deinem Geiste",
                ar: "ولروحك أيضا",
                cop_cop: "",
                ar_de: "",
                cop_ar: "كيه طو إبنفماتى سو",
            },
            {
                id: 5,
                speaker: "Priester",
                cop_ar: "",
                de: "O Urheber des Lebens , König der Ewigkeiten Gott, vor dem jedes Knie  sich beugt im Himmel und auf Erden und unter der Erde! Vor dem alle sich neigen und unterwerfen mit dem Joch der Sklaverei unter die Macht des Zepters seines Königtums! Er, den die Heerscharen der Engel, die himmlischen Ränge und die Geistwesen verherrlichen mit einer Stimme ohne Unterlass seine Göttlichkeit aussprechend. Es gefällt dir, dass wir schwache Irdische dir dienen, nicht wegen der Reinheit unserer Hände, denn wir haben das Rechte auf Erden nicht getan, sondern weil es dein Willen ist, uns Elenden und Unwürdigen von deiner Reinheit zu geben. Nimm uns auf zu dir, o gütiger Menschenliebender, denn wir nähern uns deinem heiligen Altar nach deiner Gnade. Mache uns deines himmlischen Friedens würdig, der deiner Göttlichkeit entspricht und voller Erlösung ist, damit wir ihn uns gegenseitig in vollkommener Liebe geben und einander mit einem heiligen Kuss küssen.",
                ar: "یا رئيس الحياة وملك الدهور، اللهم الذي تجثو له كل ركبة ما في السـمـوات ومـا على الأرض ومـا تحت الأرض، الذى الكل مـذلول وخاضع بعتق العبـودية تحت خـضـوع قضيب ملكه، الذي تمجـده لأجناد الملائكية، والطغمات السمائية، والطبائع العقلية، بصوت لا يسكت ناطق بألوهيته. وإِذ سررت بنا نحن أيضا الضعفاء الأرضيين أن نخدمك، لا من أجل نقاوة أيدينا، لأننا لم نفعل الصلاح على الأرض، بل مريداً أن تعطينا نحن البائسين غير المستحـقين من طهرك، اقبلنا ليك أيها الصالح مـحب البشر إذ ندنو من مـذبحك المقدس ككثرة رحمتك. واجعلنا أهلاً للسلام السمائي اللائق بلاهوتك والمملوء خلاصاً، لنعطيه بعضنا لبعض بمحبة كاملة، ونقبل بعضنا بعضاً بقبلة مقدسة. ",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 6,
                speaker: "Diakon",
                cop_de: "",
                de: "Betet für den vollkommenen Frieden, für die Liebe und die apostolischen reinen Küsse.",
                ar: "صلوا من أجل السلام الكامل والمحبة والقبلة الطاهرة الرسولية",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إبروس افكصاستيه إي برتيس تيه لياس إيرينيس كيه آغابيس كيه طون آجيون إسباسمون طون أبوسطولون",
            },
            {
                id: 7,
                speaker: "Volk",
                cop_de: "",
                de: "Herr erbarme dich",
                ar: "يارب ارحم ",
                cop_cop: "",
                ar_de: "",
                cop_ar: "كيريه ليسون",
            },
            {
                id: 8,
                speaker: "Priester",
                cop_ar: "",
                de: "Nicht aus niedriger Gesinnung, die dir Ehrfurcht verweigert, nicht mit trügerischen Gedanken voll bösen Verrats, ohne dass unser Willen mit Boshaftigkeit übereinstimmt,  sondern aus dem Wunsch unserer Seelen und dem Jubel unserer Herzen, weil wir das große vollkommene Zeichen, das der Liebe deines einziges Sohnes gehört, erhalten haben. Weise uns, deine Diener, wegen des Makels unserer Sünden nicht zurück, weil du als Schöpfer unserer Natur weißt, daß kein von einer Frau Geborener vor dir gerechtfertigt ist. Mache uns also bereit, o Herr, mit reinem Herzen und mit von deiner Gnade erfüllter Seele vor dir zu stehen und dieses heilige, lebendige, geistige und unblutige Opfer  darzubringen zum Nachlass unserer Sünden und zur Vergebung der Unwissenheit deines Volkes, denn du bist ein gnädiger und barmherziger Gott.",
                ar: "لا بحاسة مرذولة رافضة لمخافتك. ولا بفكر غاش مملوء من شر الخائن، غير متفقة نياتنا في الخبث، بل برغبة أنفسنا وتهليل قلوبنا، إذ لنا العلامة العظيمة الكاملة التي لمحبة ابنك الوحيد ولا تطرحنا نحن عبيدك من أجل دنس خطايانا، لأنك أنت العارف كخالق جبلتنا أنه ليس مولود إمرأة يتزكي أمامك. فأجعلنا إذاً أهلا يا سيدنا بقلب طاهر ونفس مملوءة من نعمتك أن نقف أمامك ونقدم لك هذه الصعيدة المقدسة الناطقة الروحانية غير الدموية صفحاً لزلاتنا وغفراناً لجهالات شعبك لأنك أنت إله رؤوف متحنن.",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 9,
                speaker: "Diakon",
                cop_de: "",
                de: "Küsst einander mit einem heiligen Kuss. (Herr erbarme Dich)* 3 Ja o Herr Jesus Christus, Sohn Gottes, erhöre uns und erbarme Dich unser. Tretet heran nach der Vorschrift, steht in Ehrfurcht und schaut nach Osten. Wir hören.",
                ar: ".قبلوا بعضكم بعضاً بقبلةٍ مقدسة. (يارب ارحم)* ۳ نعم يارب الذي هو يسوع المسيح ابن الله الحي، اسمعنا وارحمنا. تقدموا تقدموا تقدموا على الرسم، قفوا برعدة، والي الشرق أنظروا. ننصت",
                cop_cop: "",
                ar_de: "",
                cop_ar:
                    "أسـپـاذسـتي ألليلوس إن فـيلـيـمـاتی  آجـيو. (كيريي إليسوس) * ۳ نای كيريي إيتي فای پي إيسـوس پي إخـرسـتـوس إبشير إم إفنوتى سوتيم إيرون أووه ناي نان. إبروسفرين كاطا إطربو إستـاثيتي كـاطـا إطرومـوايس أناطولاس إفليـبساتـي إبروس خـومين. ",
            },
            {
                id: 10,
                speaker: "Volk",
                cop_de: "",
                de: "Durch die Fürsprache der Mutter Gottes, der Heiligen Maria, vergib uns, o Herr, unsere Sünden durch Deine Gnade.Wir beten dich an, o Christus, zusammen mit deinem guten Vater, und dem Heiligen Geist,denn du bist (auferstanden/gekommen) und hast uns erlöst. Erbarmen des Friedens, Opfer des Lobes ",
                ar: "بشفاعات والدة الإله القديسة مريم يارب انعم لنا بمغفرة خطايانا نسجد لك أيها المسيح مع أبيك الصالح والروح القدس لأنك (أتيت/قُمت) وخلصتنا رحمة السلام ذبيحة التسبيح",
                cop_cop: "",
                ar_de: "",
                cop_ar:
                    "هيتين نيه إبريسفيا إنتيه تى ثيه أوطوكوس إثؤواب ماريا: إبتشويس آرى إهموت نان إمبى كو إيفول إنتيه نين نوفي. تين أوأوشت إمموك أو بخرستوس: نيم بيك يوت إن آغاثوس: جيه (آك إي/أكطونك) أكسوتي إممون: إيه ليه أوس إيرينيس ثي سيا إيه نيه ثيه أوس",
            },
            {
                id: 11,
                speaker: "Priester",
                cop_de: "",
                de: "Der Herr sei mit euch allen",
                ar: "الرب مع جميعكم.",
                cop_cop: "",
                ar_de: "",
                cop_ar: "أوكيريوس ميه طا بانضون إممون",
            },
            {
                id: 12,
                speaker: "Volk",
                cop_de: "",
                de: "Und mit deinem Geiste",
                ar: "ومع روحك أيضاً",
                cop_cop: "",
                ar_de: "",
                cop_ar: "كيه ميه طا طو إبنفما طوسو",
            },
            {
                id: 13,
                speaker: "Priester",
                cop_de: "",
                de: "Erhebt Eure Herzen !",
                ar: "إرفعوا قلوبكم",
                cop_cop: "",
                ar_de: "",
                cop_ar: "آنو إيمون طاذكارذياس",
            },
            {
                id: 14,
                speaker: "Volk",
                cop_de: "",
                de: "Wir haben sie beim Herrn",
                ar: "هي عند الرب",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إيه خومين إبروس طون كيريون",
            },
            {
                id: 15,
                speaker: "Priester",
                cop_de: "",
                de: "Lasst uns dem Herrn danken",
                ar: "فلنشكر الرب",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إيفخاريستى صومين طو كيريو",
            },
            {
                id: 16,
                speaker: "Volk",
                cop_de: "",
                de: "Würdig und recht",
                ar: "مستحق وعادل",
                cop_cop: "",
                ar_de: "",
                cop_ar: "أكسيون كيه ذى كيه أون",
            },
            {
                id: 17,
                speaker: "Priester",
                cop_ar: "",
                de: "Würdig und recht, würdig und recht, würdig und recht: Es ist in Wahrheit würdig und recht, heilig, angemessen und nützlich für unsere Seelen, unsere Leiber und unseren Geist! Der du bist, Meister, Herr, Gott, Vater, Allmächtiger ! Zu jeder Zeit und an jedem Ort deiner Herrschaft, oben wir dich, preisen wir dich, segnen wir dich, dienen wir dir, beten wir dich an, danken dir und verherrlichen dich. Und wir bekennen uns vor dir Tag und Nacht mit nie ruhenden Lippen, mit unruhigen Herzen und mit Lobpreis ohne Unterlass. Du bist es, der die Himmel geschaffen hat und was in den Himmeln ist, die Erde und was auf ihr ist, die Meere, Flüsse, Wasserquellen und Seen und alles was darin ist Du bist es, der den Menschen nach deinem Bild und dir ähnlich erschaffen und alle übrigen Dinge durch deine Weisheit geschaffen hat, durch dein wahres Licht, dein eingeborener Sohn, unser Herr, Gott, Erlöser und unser aller König, Jesus Christus, durch den wir danken und dir mit ihm und dem Heiligen Geist, der Heiligen Dreifaltigkeit, die eines Wesens und untrennbar ist, dieses lebendige Opfer darbringen und diesen unblutigen Dienst verrichten. Dieses, was alle Völkerschaften dir darbringen! Vom Osten zum Westen und vom Norden zum Süden. Denn dein Name, o Herr, ist groß vor allen Völkerschaften, und an jedem Ort werden deinem heiligen Namen Räucherwerk und reine Opfer wie diese Opfergabe und Gabe dargebracht. ",
                ar: "مستحق وعادل مستحق وعادل مستحق وعادل لأنه بالحقيقة  مستحق وعادل ومقدس ولائق ونافع لنفوسنا واجسادنا وارواحنا ايها الكائن السيد الرب الله الآب ضابط الكل في كل زمان وبكل مكان لربوبيتك أن نسبحك ونرتل لك ونباركك ونخدمك ونسجد لك ونشكرك ونمجدك. ونعترف لك ليلاً ونهاراً بشفاه غير هادئة وقلب لا يسكت وتمجيدات لا تنقطع.انت الذي خلقت السموات وما في السموات والأرض وكل ما فيها البحار والأنهار والينابيع والبحيرات وما في جميعها.انت هو الذي خلقت الانسان كصورتك وكشبهك وخلقت كل الاشياء بحكمتك نورك الحقيقي ابنك الوحيد ربنا والهنا ومخلصنا وملكنا كلنا يسوع المسيح هذا الذي من قبلة نشكر ونقرب لك معه ومع الروح القدس الثالوث المقدس المساوي غير المفترق هذه الذبيحة الناطقة وهذه الخدمة غير الدموية. هي التي تقربها لك جميع الأمم. من مشارق الشمس الي مغاربها ومن الشمال الي الجنوب لأن اسمك عظيم يارب في جميع الامم وفي كل مكان يقدم بخور لاسمك القدوس وصعيدة طاهره وعلي هذه الذبيحة وهذا القربان.",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 18,
                speaker: "Diakon",
                cop_de: "",
                de: "Wer sitzt, stehe auf!",
                ar: "أيها الجلوس قفوا",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إي كاثي ميه ني أناسثيتيه",
            },
            {
                id: 19,
                speaker: "Priester",
                cop_ar: "",
                de: "Denn dein Name, o Herr, ist groß vor allen Völkerschaften, und an jedem Ort werden deinem heiligen Namen Räucherwerk und reine Opfer wie diese Opfergabe und Gabe dargebracht. und über jedem Namen, der genannt werden wird, nicht nur in dieser Zeit, sondern auch in der zukünftigen Welt.",
                ar: "لأنك انت هو الذي فوق كل رئاسة وكل سلطان وكل قوة وكل سيادة وكل اسم يسمي ليس في هذا الدهر فقط بل وفي الآتي.",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 20,
                speaker: "Diakon",
                cop_de: "",
                de: "Schaut nach Osten!",
                ar: "وإلى الشرق انظروا",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إس أناطولاس إفليب صاتيه",
            },
            {
                id: 21,
                speaker: "Priester",
                cop_ar: "",
                de: "Du bist es, vor dem abertausende und aber zehntausende Engel, Erzengel und die Heiligen stehen und dienen. Du bist es, vor dem deine beiden guten Wesen stehen, die sechs Flügel und viele Augen haben, die Seraphim und Cherubim. ",
                ar: "أنت الذي يقوم أمامك ألوف ألوف وربوات ربوات الملائكة ورؤساء الملائكة المقدسين يخدمونك. انت الذي يقوم أمامك الكائنات الكريمان جداً ذو الستة الأجنحه الكثيرا الاعين السيرافيم والشاروبيم. فبجناحين يغطون وجوههم من اجل لاهوتك الذي لا يستطاع النظر إليه ولا التفكر فيه. وباثنين يغطون أرجلهم ويطيرون بالاثنين الآخرين.لأن في كل زمان يقدسك كل أحد. لكن مع كل من يقدسك اقبل تقديسنا منا نحن أيضاً يارب إذ نسبحك معهم قائلين",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 22,
                speaker: "Volk",
                cop_de: "",
                de: "Heilig, heilig, heilig ist der Herr der Heerscharen , der Himmel und die Erde sind erfüllt von deiner heiligen Herrlichkeit",
                ar: "قدوس قدوس قدوس رب الصاباؤوت السماء والأرض مملوءتان من مجدك الأقدس",
                cop_cop: "",
                ar_de: "",
                cop_ar: "جيه آجيوس آجيوس آجيوس كيريوس صافاؤوت: إبلى ريس أو أورانس كيه إى جى تيس آجياس صوذوكسيس",
            },
            {
                id: 23,
                speaker: "Priester",
                cop_de: "",
                de: "Heilig Heilig Heilig",
                ar: "قدوس، قدوس، قدوس",
                cop_cop: "",
                ar_de: "",
                cop_ar: "آجيوس، آجيوس، آجيوس",
            },
            {
                id: 24,
                speaker: "Priester",
                cop_ar: "",
                de: "Heilig bist du Herr der Heerscharen, der Himmel und die Erde sind erfüllt von deiner heiligen Herrlichkeit. O Herr, unser Gott, der Himmel und die Erde sind wahrhaftig erfüllt von deiner heiligen Herrlichkeit, durch deinen eingeborenen Sohn, unseren Herrn, Gott, Erlöser und unser aller König Jesus Christus: Erfülle diese Opfergabe, die dir gehört, o Herr, mit dem Segen, der von dir ist. Durch die Herabkunft deines Heiligen Geistes auf sie. ",
                ar: "قدوس رب الجنود السماء والأرض مملوءتان من مجدك الأقدس، أيها الرب الهنا بالحقيقه السماء والارض مملوءتان من مجدك الأقدس، من قبل ابنك الوحيد ربنا والهنا ومخلصنا وملكنا يسوع المسيح املأ هذه الصعيدة التي لك يارب بالبركة التي من قبلك. بحلول روحك القدوس عليها",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 25,
                speaker: "Volk",
                cop_ar: "آميــــن",
                de: "Amen",
                ar: "حفا",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 26,
                speaker: "Priester",
                cop_ar: "",
                de: "Mit dem Segen segne sie",
                ar: "وبالبركة بارك",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 27,
                speaker: "Volk",
                cop_ar: "آميــــن",
                de: "Amen",
                ar: "حفا",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 28,
                speaker: "Priester",
                cop_ar: "",
                de: "Und mit der Heiligung heilige sie",
                ar: "وبالتقديس قدس",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 29,
                speaker: "Volk",
                cop_ar: "آميــــن",
                de: "Amen",
                ar: "حقا",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 30,
                speaker: "Priester",
                cop_ar: "",
                de: "Diese deine heiligen Opfergaben, die wir begonnen haben, vor dich zu legen, dieses Brot und diesen Kelch. Denn dein einziger Sohn, unser Herr, Gott und Erlöser und unser aller König Jesus Christus! In der Nacht, in der er sich selbst hingab, um für unsere Sünden zu leiden und auch den Tod, den er aus sich selbst aus seinem eigenen Willen für uns alle annahm",
                ar: "قرابينك هذه المكرمة التي بدأنا بوضعها أمامك هذا الخبز وهذه الكأس لأن ابنك الوحيد ربنا والهنا ومخلصنا وملكنا كلنا يسوع المسيح. في الليلة التي اسلم ذاته فيها ليتألم عن خطايانا والموت الذي قبله بذاته بإرادته وحده عنا كلنا.",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 31,
                speaker: "Volk",
                cop_de: "",
                de: "Wir glauben",
                ar: "نؤمــــــن",
                cop_cop: "",
                ar_de: "",
                cop_ar: "بيستيف أومين",
            },
            {
                id: 32,
                speaker: "Priester",
                cop_de: "",
                de: "Er nahm Brot in seine reinen, makellosen, unbefleckten, seligen und lebensspendenden Hände.",
                ar: "أخذ خبزاً على يديه الطاهرتين اللتين بلا عيب ولا دنس الطوباويتين المحييتين",
                cop_cop: "",
                ar_de: "",
                cop_ar: "أفتشي إن أو أويك إيجين نيف جيج إثؤواف إن آتتشنى أووه إن أتثوليف أووه إم مكاريون أووه أنريف تنخو",
            },
            {
                id: 33,
                speaker: "Volk",
                cop_de: "",
                de: "Wir glauben, dass dieses in Wahrheit so ist. Amen.",
                ar: "نؤمن أن هذا هو بالحقيقة: أمين.",
                cop_cop: "",
                ar_de: "",
                cop_ar: "تين ناهتى جيه فاى بيه خين أو ميثمى: آمين",
            },
            {
                id: 34,
                speaker: "Priester",
                cop_de: "",
                de: "Er blickte hinauf zum Himmel zu dir, der sein Vater ist, Gott und Meister eines jeden.",
                ar: "ونظر إلى فوق نحو السماء إليك الله أبيك وسيد كل أحد ",
                cop_cop: "",
                ar_de: "",
                cop_ar: "أفجوشت إى إبشوى إى إتفى هاروك فيئتيفوف إنيوت إفنوتى أووه إفنيب إنتى أوؤن نيفين",
            },
            {
                id: 35,
                speaker: "Priester",
                cop_de: "",
                de: "Er dankte",
                ar: "وشكـر",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إيه طاف شيب أهموت",
            },
            {
                id: 36,
                speaker: "Volk",
                cop_ar: "آميـــــن",
                de: "Amen",
                ar: "حقا",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 37,
                speaker: "Priester",
                cop_de: "",
                de: "Er segnete es",
                ar: "وباركه",
                cop_cop: "",
                ar_de: "",
                cop_ar: "أف إسمو إيه روف",
            },
            {
                id: 38,
                speaker: "Volk",
                cop_ar: "آميـــــن",
                de: "Amen",
                ar: "حقا",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 39,
                speaker: "Priester",
                cop_de: "",
                de: "Und heiligte es",
                ar: "وقدسه",
                cop_cop: "",
                ar_de: "",
                cop_ar: "أف إير آجيا زين إمموف",
            },
            {
                id: 40,
                speaker: "Volk",
                cop_ar: "آميـــــن",
                de: "Amen",
                ar: "حقا",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 41,
                speaker: "Volk",
                cop_de: "",
                de: "Wir glauben, bekennen und verherrlichen",
                ar: "نؤمن ونعترف ونمجد",
                cop_cop: "",
                ar_de: "",
                cop_ar: "بستيف أومين كيه أومولوغومين كيه ذوكصازومين",
            },
            {
                id: 42,
                speaker: "Priester",
                cop_de: "",
                de: "Er teilte und gab es seinen heiligen, ehrwürdigen Jüngern und reinen Aposteln und sprach: Nehmt, esst alle davon, denn dies ist mein Leib, der für euch und für viele gebrochen wird zur Vergebung der Sünden. Tut dies zu meinem Gedächtnis",
                ar: "وقسمه وأعطاه لتلاميذه المكرمين  القديسين ورسله الأطهار قائلاً: خذوا كلوا منه كلكم، لأن هذا هو جسدي. الذي يقسم عنكم وعن كثيرين يعطى لمغفرة الخطايا  هذا اصنعوه لذكرى",
                cop_cop: "",
                ar_de: "",
                cop_ar: "آف فشف أفتيف إننى إيتي نوف إن أجيوس إم ماثيتيس أووه إن أبو سطولوس إثؤواب إفجو إمموس جى تشى أؤوم إيفول إنخيتف تيرو فاى غار بى باسوما إتونافشف  إيجين ثينو نيم هان كى ميش إنسى تيف إى إبكو إيفول انتى نى نوفى فاى أريتف إيبا إير افميفى",
            },
            {
                id: 43,
                speaker: "Volk",
                cop_de: "",
                de: "Dies ist es in Wahrheit. Amen",
                ar: "هذا هو بالحقيقة: آمين",
                cop_cop: "",
                ar_de: "",
                cop_ar: "فاى بيه خين أوميثمي: آمين",
            },
            {
                id: 44,
                speaker: "Priester",
                cop_de: "",
                de: "Ebenso nahm er nach dem Mahl den Kelch, mischte Wein und Wasser",
                ar: "وهكذا الكأس أيضاً  من بعد العشاء مزجها من ثمرة الكرمة وماء",
                cop_cop: "",
                ar_de: "",
                cop_ar: "باى ريتى أون بى كى أفوت مينينسا بى ذيبنون أفثوطف إيفول خين أو إرب نيم أو موؤو",
            },
            {
                id: 45,
                speaker: "Priester",
                cop_de: "",
                de: "Er dankte",
                ar: "وشكـر",
                cop_cop: "",
                ar_de: "",
                cop_ar: "إيه طاف شيب أهموت",
            },
            {
                id: 46,
                speaker: "Volk",
                cop_ar: "آميـــــن",
                de: "Amen",
                ar: "حقا",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 47,
                speaker: "Priester",
                cop_ar: "",
                de: "Er segnete es",
                ar: "وباركه",
                cop_cop: "",
                ar_de: "",
                cop_ar: "أف إسمو إيه روف",
            },
            {
                id: 48,
                speaker: "Volk",
                cop_ar: "آميـــــن",
                de: "Amen",
                ar: "حقا",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 49,
                speaker: "Priester",
                cop_de: "",
                de: "Und heiligte es",
                ar: "وقدسه",
                cop_cop: "",
                ar_de: "",
                cop_ar: "أف إير آجيا زين إمموف",
            },
            {
                id: 50,
                speaker: "Volk",
                cop_ar: "آميـــــن",
                de: "Amen",
                ar: "حقا",
                cop_cop: "",
                ar_de: "",
                cop_ar: "",
            },
            {
                id: 51,
                speaker: "Volk",
                cop_de: "",
                de: "Wiederum glauben, bekennen und verherrlichen wir",
                ar: "وأيضاً نؤمن ونعترف ونمجد",
                cop_cop: "",
                ar_de: "",
                cop_ar: "كيه بالين بستيف أومين كيه أومولوغومين كيه ذوكصازومين",
            },
            {
                id: 52,
                speaker: "Priester",
                cop_de: "",
                de: "Er kostete davon und gab ihn seinen heiligen, ehrwürdigen Jüngern und reinen Aposteln mit den Worten: Nehmt, trinkt alle daraus, denn dies ist mein Blut des neuen Bundes, das für euch und für viele vergossen wird und hingegeben zur Vergebung der Sünden. „Tut dies zu meinem Gedächtnis“.",
                ar: "وذاق وأعطاها أيضاً لتلاميذه المكرمين القديسين ورسله الأطهار قائلاً: خذوا اشربوا منها كلكم لأن هذا هو دمى الذي للعهد الجديد الذى يسفك عنكم وعن كثيرين يعطى لمغفرة الخطايا هذا اصنعوه لذكري",
                cop_cop: "",
                ar_de: "",
                cop_ar: "آف جيمتيبى أف تيف أون إنى إيتينوف إن أجيوس إم ماثيتيس أووه إن ابسطولوس اثؤواف إفجو إمموس جى تشى سو إيفول إنخيتف تيرو فاى غار بى باإسنوف إنتى تى ذياثيكى إمفيري إيطو نافونف إيفول إبجين ثينو نيم هان كى ميش انسيتيف إى إبكو ايفول انتى نى نوفى فاى أريتف إيبا إير افميفئ",
            },
            {
                id: 53,
                speaker: "Volk",
                cop_de: "",
                de: "Dies ist es auch in Wahrheit. Amen",
                ar: "وهذا هو أيضاً بالحقيقة آمين",
                cop_cop: "",
                ar_de: "",
                cop_ar: "فاى أون بى خين أو ميثمي آمين",
            },
            {
                id: 54,
                speaker: "Priester",
                cop_de: "",
                de: "Denn jedes Mal, wenn ihr von diesem Brot esst, und aus diesem Kelch trinkt, verkündet ihr meinen Tod, bekennt meine Auferstehung und erinnert euch meiner, bis ich wieder komme.",
                ar: "لأن كل مرة تأكلون من هذا الخبز وتشربون من هذه الكأس تبشرون بموتي وتعترفون بقيامتي وتذكروني إلى أن أجئ ",
                cop_cop: "",
                ar_de: "",
                cop_ar: "سوب غار نيفين إيتين نا أو أوم إيفول خين باى أو يك فاى أووه إنتى تين سو إيفول خين باى أفوت فاى إيرييتين هى أو يش إمبامو إيرتين إير أمولوجين إنتا أناسطاسيس إيرى تين إيرى إمباميفئي شاتى إى",
            },
            {
                id: 55,
                speaker: "Volk",
                cop_de: "",
                de: "Amen, Amen, Amen, deinen Tod, o Herr, verkünden wir, deine heilige Auferstehung und deine Himmelfahrt bekennen wir. Wir loben dich, wir preisen dich, wir danken dir, o Herr, und wir bitten dich, unser Gott!",
                ar: " امين امين امين بموتك يارب نبشر وبقيامتك المقدسة وصعودك إلى السموات نعترف نسبحُك نباركُك نشكرُك يارب ونتضرعُ إليكَ يا إلَهنا.",
                cop_cop: "",
                ar_de: "",
                cop_ar: "آمين آمين آمين طون ثاناطون صو كيريه كاطانجيه لومين: كيه تين آجيان صو آناسطاسين: كيه تين أناليبسين صو إنتيس أورانيس سيه أومولوغومين: سيه إيه نومين سيه إفلوغومين سيه إفخاريس طومين كيريه: كيه ذيه أو ميه طا سو أوثيه أوس إيمون",
            },
            {
                id: 56,
                speaker: "Priester",
                cop_ar: "",
                de: "O Gott, Vater, Allmächtiger, während wir jetzt den Tod deines eingeborenen Sohnes, unseres Herrn, Gottes, Erlösers und unser aller König, Jesus Christus , verkünden und wir seine heilige Auferstehung , seine Auffahrt in den Himmel und sein Sitzen zu deiner Rechten bekennen, Vater, erwarten wir seine zweite Erscheinung, die vom Himmel kommt, furchterregend und voller Herrlichkeit am Ende dieser Zeit, in der er kommt, um den Erdkreis in Gerechtigkeit zu richten und jedem nach seinem Werk zu vergelten , ob es gut war oder böse .",
                ar: "فالآن يا الله الآبُ ضابطُ الكُلِّ، فيما نحنُ نُبشِّرُ بموتِ ابنِكَ الوحيدِ ربِّنا وإلهِنا ومُخَلِّصِنا ومَلِكِنا كُلِّنا يسوع المسيح. , ونعتَرِفُ بقيامَتِهِ المُقَدَّسَةِ، وصُعودِهِ إلى السَّمَواتِ، وجُلوسِهِ عن يَمينِكَ أيُّهَاالآبُ., وننتظرُ ظُهُورَهُ الثَّاني، الآتي مِنَ السَّمَواتِ، المَخوفَ المَملوءَ مجداً، في انقِضاءِ هذا الدَّهْرِ. هذا الَّذي يأتي فيهِ ليدينَ المسكونَةَ بالعدلِ. . ويُعطي كُلَّ واحِدٍ كأعمالِهِ، إن كانَ خيراً وإن كانَ شراً.",
                cop_cop: "Ϯⲛⲟⲩ ⲟⲩⲛ Ⲫⲛⲟⲩϯ Ⲫⲓⲱⲧ Ⲡⲓⲡⲁⲛⲧⲟⲣⲁⲧⲱⲣ : ⲉⲛϩⲓⲱⲓϣ ⲙ̀ⲫⲙⲟⲩ ⲙ̀ⲡⲉⲣⲙⲟⲛⲟⲅⲉⲛⲏⲥ ⲛ̀Ϣⲏⲣⲓ Ⲡⲉⲛϭⲟⲓⲥ ⲟⲩⲟϩ Ⲡⲉⲛⲛⲟⲩϯ ⲟⲩⲟϩ Ⲡⲉⲛⲥⲱⲧⲏⲣ ⲟⲩⲟϩ ⲡⲉⲛⲟⲩⲣⲟ ⲧⲏⲣⲉⲛ Ⲓⲏⲥⲟⲩⲥ Ⲡⲓⲭⲣⲓⲥⲧⲟⲥ. Ⲉⲛⲉⲣⲟ̀ⲙⲟⲗⲟⲅⲓⲛ ⲛ̀ⲧⲉϥⲁ̀ⲛⲁⲥⲧⲁⲥⲓⲥ ⲉ̀ⲑⲟⲩⲁⲃ : ⲛⲉⲙ ⲡⲉϥϫⲓⲛϣⲉ ⲉ̀ⲡϣⲱⲓ ⲉ̀ⲛⲓⲫⲏⲟⲩⲓ̀ : ⲛⲉⲙ ⲡⲉϥϫⲓⲛϩⲉⲙⲥⲓ ⲥⲁⲧⲉⲣⲟⲩⲓⲛⲁⲙ Ⲫⲓⲱⲧ. Ⲉⲛϫⲟⲩϣⲧ ⲉ̀ⲃⲟⲗ ϧⲁⲧⲏⲛ ⲛ̀ⲧⲉϥⲙⲁϩⲥⲛⲟⲩϯ ⲙ̀ⲡⲁⲣⲟⲩⲥⲓⲁ̀: ⲉⲑⲛⲏⲟⲩ ⲉ̀ⲃⲟⲗϧⲉⲛ ⲛⲓⲫⲏⲟⲩⲓ̀ : ⲉⲧⲟⲓ ⲛ̀ϩⲟϯ ⲟⲩⲟϩ ⲉⲑⲙⲉϩ ⲛ̀ⲱⲟⲩ : ϧⲉⲛ ϯⲥⲩⲛⲧⲉⲗⲓⲁ̀ ⲛ̀ⲧⲉ ⲡⲁⲓⲉ̀ⲱⲛ. Ⲑⲁⲓ ⲉ̀ⲧⲉϥⲛⲏⲟⲩ ⲛ̀ϧⲏⲧⲥ ⲉ̀ⲧϩⲁⲡ ⲉ̀ϯⲟⲓⲣⲟⲩⲙⲉⲛⲏ ϧⲉⲛ ⲟⲩⲙⲉⲑⲙⲏⲓ. Ⲛⲉⲙ ⲉ̀ϯ ⲙ̀ⲡⲓⲟⲩⲁⲓ ⲡⲓⲟⲩⲁⲓ ⲕⲁⲧⲁ ⲛⲉϥϩ̀ⲃⲏⲟⲩⲓ : ⲓ̀ⲧⲉ ⲟⲩⲡⲉⲑⲛⲁⲛⲉϥ ⲓ̀ⲧⲉ ⲟⲩⲡⲉⲧϩⲱⲟⲩ.",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 57,
                speaker: "",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 56,
                speaker: "",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 56,
                speaker: "",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 56,
                speaker: "",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 56,
                speaker: "",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 56,
                speaker: "",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 56,
                speaker: "",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 56,
                speaker: "",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },
            {
                id: 56,
                speaker: "",
                cop_ar: "",
                de: "",
                ar: "",
                cop_cop: "",
                ar_de: "",
                cop_de: "",
            },




        ],
    },
}
